USE mko;

DROP TABLE music;

CREATE TABLE music (
  id INT AUTO_INCREMENT,	-- 0, 1, ...
  disc INT NOT NULL,		-- 0, 1, ...
  track INT NOT NULL,		-- 0, 1, ...
  composer VARCHAR(32),		-- e.g. "Orff, Carl"
  work VARCHAR(48),		-- e.g. "Catulli Carmina"
  title VARCHAR(64),		-- e.g. "Desine de Quoquam"
  PRIMARY KEY(id)
);

INSERT INTO music (disc,track,composer,work,title)
  VALUES(001,01,"Glass, Philip","North Star","Etoile Polaire"),
  (001,02,"Glass, Philip","North Star","Victor's Lament"),
  (001,03,"Glass, Philip","North Star","River Run"),
  (001,04,"Glass, Philip","North Star","Mon Pere, Mon Pere"),
  (001,05,"Glass, Philip","North Star","Are Years What?"),
  (001,06,"Glass, Philip","North Star","Lady Day"),
  (001,07,"Glass, Philip","North Star","Ange des Orages"),
  (001,08,"Glass, Philip","North Star","Ave"),
  (001,09,"Glass, Philip","North Star","Ik-ook"),
  (001,10,"Glass, Philip","North Star","Montage"),
  (001,11,"Glass, Philip","Songs from the Trilogy","Protest"),
  (001,12,"Glass, Philip","Songs from the Trilogy","Evening Song"),
  (001,13,"Glass, Philip","Songs from the Trilogy","Hymn to the Sun"),
  (001,14,"Glass, Philip","Songs from the Trilogy","Trial, Prison"),
  (001,15,"Glass, Philip","Songs from the Trilogy","Akhnaten and Nefertiti"),
  (001,16,"Glass, Philip","Songs from the Trilogy","Kuru Field of Justice"),
  (001,17,"Glass, Philip","Songs from the Trilogy","Knee 1"),
  (001,18,"Glass, Philip","Songs from the Trilogy","Tolstoy Farm"),
  (001,19,"Glass, Philip","Songs from the Trilogy","Window of Appearances"),
  (002,01,"Glass, Philip","Songs from the Trilogy","Bed"),
  (002,02,"Glass, Philip","Songs from the Trilogy","Epilogue"),
  (002,03,"Glass, Philip","Songs from the Trilogy","Knee 5"),
  (002,04,"Glass, Philip","Glassworks","Opening"),
  (002,05,"Glass, Philip","Glassworks","Floe"),
  (002,06,"Glass, Philip","Glassworks","Islands"),
  (002,07,"Glass, Philip","Glassworks","Rubric"),
  (002,08,"Glass, Philip","Glassworks","Facades"),
  (002,09,"Glass, Philip","Glassworks","Closing"),
  (002,10,"Glass, Philip","Songs from Liquid Days","Freezing"),
  (002,11,"Glass, Philip","Songs from Liquid Days","Lightning"),
  (003,01,"Jarre, Jean-Michel","Chronologie","Chronologie 1"),
  (003,02,"Jarre, Jean-Michel","Chronologie","Chronologie 2"),
  (003,03,"Jarre, Jean-Michel","Chronologie","Chronologie 3"),
  (003,04,"Jarre, Jean-Michel","Chronologie","Chronologie 4"),
  (003,05,"Jarre, Jean-Michel","Chronologie","Chronologie 5"),
  (003,06,"Jarre, Jean-Michel","Chronologie","Chronologie 6"),
  (003,07,"Jarre, Jean-Michel","Chronologie","Chronologie 7"),
  (003,08,"Jarre, Jean-Michel","Chronologie","Chronologie 8"),
  (003,09,"Jarre, Jean-Michel","Magnetic Fields","Magnetic Fields 1"),
  (003,10,"Jarre, Jean-Michel","Magnetic Fields","Magnetic Fields 2"),
  (003,11,"Jarre, Jean-Michel","Magnetic Fields","Magnetic Fields 3"),
  (003,12,"Jarre, Jean-Michel","Magnetic Fields","Magnetic Fields 4"),
  (003,13,"Jarre, Jean-Michel","Magnetic Fields","Magnetic Fields 5"),
  (004,01,"Jarre, Jean-Michel","Waiting for Cousteau","Calypso 1"),
  (004,02,"Jarre, Jean-Michel","Waiting for Cousteau","Calypso 2"),
  (004,03,"Jarre, Jean-Michel","Waiting for Cousteau","Calypso 3"),
  (004,04,"Jarre, Jean-Michel","Waiting for Cousteau","Waiting for Cousteau"),
  (004,05,"Jarre, Jean-Michel","The Essential Jean-Michel Jarre","Oxygene 4"),
  (004,06,"Jarre, Jean-Michel","The Essential Jean-Michel Jarre","Equinoxe 5"),
  (004,07,"Jarre, Jean-Michel","The Essential Jean-Michel Jarre","Oxygene 2"),
  (004,08,"Jarre, Jean-Michel","The Essential Jean-Michel Jarre","Orient Express"),
  (004,09,"Jarre, Jean-Michel","The Essential Jean-Michel Jarre","Magnetic Fields 1"),
  (004,10,"Jarre, Jean-Michel","The Essential Jean-Michel Jarre","Fishing Junks at Sunset"),
  (004,11,"Jarre, Jean-Michel","The Essential Jean-Michel Jarre","The Overture"),
  (004,12,"Jarre, Jean-Michel","The Essential Jean-Michel Jarre","Equinoxe 4"),
  (004,13,"Jarre, Jean-Michel","Revolutions","Industrial Revolution 2"),
  (005,01,"Vangelis","Conquest of Paradise","Opening"),
  (005,02,"Vangelis","Conquest of Paradise","Conquest of Paradise"),
  (005,03,"Vangelis","Conquest of Paradise","Monastery of La Rabida"),
  (005,04,"Vangelis","Conquest of Paradise","City of Isabel"),
  (005,05,"Vangelis","Conquest of Paradise","Light and Shadow"),
  (005,06,"Vangelis","Conquest of Paradise","Deliverance"),
  (005,07,"Vangelis","Conquest of Paradise","West across the Ocean Sea"),
  (005,08,"Vangelis","Conquest of Paradise","Eternity"),
  (005,09,"Vangelis","Conquest of Paradise","Hispanola"),
  (005,10,"Vangelis","Conquest of Paradise","Moxica and the Horse"),
  (005,11,"Vangelis","Conquest of Paradise","Twenty Eighth Parallel"),
  (005,12,"Vangelis","Conquest of Paradise","Pinta, Nina, Santa Maria"),
  (005,13,"Vangelis","Oceanic","Bon Voyage"),
  (005,14,"Vangelis","Oceanic","Sirens' Whispering"),
  (005,15,"Vangelis","Oceanic","Dreams of Surf"),
  (005,16,"Vangelis","Oceanic","Spanish Harbour"),
  (006,01,"Vangelis","Oceanic","Islands of the Orient"),
  (006,02,"Vangelis","Oceanic","Fields of Coral"),
  (006,03,"Vangelis","Oceanic","Aquatic Dance"),
  (006,04,"Vangelis","Oceanic","Memories of Blue"),
  (006,05,"Vangelis","Oceanic","Song of the Seas"),
  (006,06,"Vangelis","Themes","BladeRunner Title Theme"),
  (006,07,"Vangelis","Themes","Missing Title Theme"),
  (006,08,"Vangelis","Themes","L'Enfant"),
  (006,09,"Vangelis","Themes","Hymn"),
  (006,10,"Vangelis","Themes","Chung Kuo"),
  (006,11,"Vangelis","Themes","The Tao of Love"),
  (006,12,"Vangelis","Themes","Antarctica Title Theme"),
  (006,13,"Vangelis","Themes","BladeRunner Love Theme"),
  (006,14,"Vangelis","Themes","Mutiny on the Bounty Opening Theme"),
  (006,15,"Vangelis","Themes","Mutiny on the Bounty Closing Theme"),
  (007,01,"Vangelis","Themes","Memories of Green"),
  (007,02,"Vangelis","Themes","La Petite Fille de la Mer"),
  (007,03,"Vangelis","Themes","Chariots of Fire"),
  (007,04,"Tangerine Dream","Zeit","Birth of Liquid Pleiades"),
  (007,05,"Tangerine Dream","Zeit","Nebulous Dawn"),
  (007,06,"Tangerine Dream","Zeit","Origin of Supernatural Probabilities"),
  (008,01,"Rossini, Gioacchino A.","World's Greatest Overtures","William Tell Overture"),
  (008,02,"Smetana, Bredrich","World's Greatest Overtures","Bartered bride"),
  (008,03,"Strauss, Johann","World's Greatest Overtures","Die Fledermaus"),
  (008,04,"Offenbach, Jacques","World's Greatest Overtures","Orpheus in the Underworld"),
  (008,05,"Tchaikovsky, Piotr I.","World's Greatest Overtures","1812 Overture"),
  (008,06,"Schubert, Franz P.","World's Greatest Overtures","Rosamunde"),
  (008,07,"Brahms, Johannes","World's Greatest Overtures","Academic Festival Overture"),
  (009,01,"Suppe, Franz von","World's Greatest Overtures","Poet and Peasant"),
  (009,02,"Mendelssohn, Felix","World's Greatest Overtures","Hebrides Overture"),
  (009,03,"Oldfield, Mike","Tubular Bells","Tubular Bells"),
  (010,01,"Weber, Andrew L.","Phantom of the Opera","Overture"),
  (010,02,"Weber, Andrew L.","Phantom of the Opera","Think of Me"),
  (010,03,"Weber, Andrew L.","Phantom of the Opera","Angel of Music"),
  (010,04,"Weber, Andrew L.","Phantom of the Opera","Mirror"),
  (010,05,"Weber, Andrew L.","Phantom of the Opera","Phantom of the Opera"),
  (010,06,"Weber, Andrew L.","Phantom of the Opera","Music of the Night"),
  (010,07,"Weber, Andrew L.","Phantom of the Opera","Prima Donna"),
  (010,08,"Weber, Andrew L.","Phantom of the Opera","All I Ask of You"),
  (010,09,"Weber, Andrew L.","Phantom of the Opera","Entr'Acte"),
  (010,10,"Weber, Andrew L.","Phantom of the Opera","Masquerade"),
  (010,11,"Weber, Andrew L.","Phantom of the Opera","Wishing You were somehow Here Again "),
  (010,12,"Weber, Andrew L.","Phantom of the Opera","Point of No Return"),
  (010,13,"Weber, Andrew L.","Phantom of the Opera","Down Once More"),
  (010,14,"Tangerine Dream","Zeit","Zeit"),
  (011,01,"Amsterdam Street Organ","Blaze Away","Medley"),
  (011,02,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,03,"Amsterdam Street Organ","Blaze Away","Falderi, Faldera"),
  (011,04,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,05,"Amsterdam Street Organ","Blaze Away","Can-Can"),
  (011,06,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,07,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,08,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,09,"Amsterdam Street Organ","Blaze Away","Cuckoo"),
  (011,10,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,11,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,12,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,13,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,14,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,15,"Amsterdam Street Organ","Blaze Away","Teddy Bear's Picnic"),
  (011,16,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,17,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,18,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,19,"Amsterdam Street Organ","Blaze Away","Waltz Medley"),
  (011,20,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,21,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,22,"Amsterdam Street Organ","Blaze Away","Unknown"),
  (011,23,"Amsterdam Street Organ","Blaze Away","Medley"),
  (011,24,"Simon and Garfunkel","The Sounds of Silence","Leaves that are Green"),
  (011,25,"Simon and Garfunkel","The Sounds of Silence","Blessed"),
  (011,26,"Simon and Garfunkel","The Sounds of Silence","Somewhere They can't find Me"),
  (011,27,"Simon and Garfunkel","The Sounds of Silence","Anji"),
  (011,28,"Simon and Garfunkel","The Sounds of Silence","Richard Corey"),
  (011,29,"Simon and Garfunkel","The Sounds of Silence","A Most Peculiar Man"),
  (011,30,"Simon and Garfunkel","The Sounds of Silence","April come She will"),
  (011,31,"Simon and Garfunkel","The Sounds of Silence","We've got A Groovey Thing goin'"),
  (012,01,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","Mrs. Robinson"),
  (012,02,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","For Emily, Wherever I may find Her"),
  (012,03,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","The Boxer"),
  (012,04,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","59th Street Bridge Song"),
  (012,05,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","The Sounds of Silence"),
  (012,06,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","I am A Rock"),
  (012,07,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","Scarborough Fair"),
  (012,08,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","Homeward Bound"),
  (012,09,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","Bridge over Troubled Water"),
  (012,10,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","America"),
  (012,11,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","Kathy's Song"),
  (012,12,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","El Condor Pasa"),
  (012,13,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","Bookends Theme"),
  (012,14,"Simon and Garfunkel","Simon and Garfunkel Greatest Hits","Cecilia"),
  (012,15,"Simon and Garfunkel","Bridge over Troubled Water","Keep The Customer Satisfied"),
  (012,16,"Simon and Garfunkel","Bridge over Troubled Water","So Long, Frank Lloyd Wright"),
  (012,18,"Simon and Garfunkel","Bridge over Troubled Water","The Only Living Boy in New York"),
  (012,19,"Simon and Garfunkel","Bridge over Troubled Water","Why don't You write Me"),
  (012,20,"Simon and Garfunkel","Bridge over Troubled Water","Bye Bye Love"),
  (012,21,"Simon and Garfunkel","Bridge over Troubled Water","Song for The Asking"),
  (012,22,"Singing Nun","Dominique","Dominique"),
  (012,23,"Singing Nun","Entre Les Etoiles","Entre Les Etoiles"),
  (012,24,"Stewart, Andy","The Muckin' o' Geordie's Byre","The Muckin' o' Geordie's Byre"),
  (012,25,"Stewart, Andy","Campbeltown Loch","Campbeltown Loch"),
  (013,01,"Storm","Gladiators","Main Theme"),
  (013,02,"Ugly Kid Joe","Gladiators","Everything about You"),
  (013,03,"Tyler, Bonnie","Gladiators","Holding out for A Hero"),
  (013,04,"Europe","Gladiators","The Final Countdown"),
  (013,05,"Meatloaf","Gladiators","Bat out of Hell"),
  (013,06,"Rainbow","Gladiators","Since You've been Gone"),
  (013,07,"Survivor","Gladiators","Burning Heart"),
  (013,08,"Toto","Gladiators","Hold the Line"),
  (013,09,"Boston","Gladiators","More than A Feeling"),
  (013,10,"Free","Gladiators","All Right Now"),
  (013,11,"Snap","Gladiators","The Power"),
  (013,12,"Starr, Edwin","Gladiators","War"),
  (013,13,"Troggs","Gladiators","Wild Thing"),
  (013,14,"Bachman Turner Overdrive","Gladiators","You ain't seen Nothing Yet"),
  (013,15,"Storm","Gladiators","Gladiators Entrance"),
  (013,16,"Warren's World","Gladiators","Medley Mix"),
  (013,17,"Storm","Gladiators","Duel"),
  (013,18,"Storm","Gladiators","Eliminator"),
  (013,19,"Storm","Gladiators","Wall"),
  (013,20,"Storm","Gladiators","Atlaspheres"),
  (013,21,"Storm","Gladiators","You're A Winner"),
  (013,22,"Storm","Gladiators","Dangerzone"),
  (013,23,"Storm","Gladiators","Hang Tough"),
  (013,24,"Storm","Gladiators","Swingshot"),
  (013,25,"Storm","Gladiators","There are No Losers"),
  (014,01,"Live and Let Die","Martin, George","James Bond Main Theme"),
  (014,02,"Live and Let Die","Martin, George","Live and Let Die"),
  (014,03,"Live and Let Die","Martin, George","Just a Closer Walk with Thee"),
  (014,04,"Live and Let Die","Martin, George","Solitaire gets Her Cards"),
  (014,05,"Live and Let Die","Martin, George","Bond meets Solitaire"),
  (014,06,"Live and Let Die","Martin, George","Whisper who dares"),
  (014,07,"Live and Let Die","Martin, George","Bond drops in"),
  (014,08,"Live and Let Die","Martin, George","Baron Samed'is Dance of Death"),
  (014,09,"Live and Let Die","Martin, George","San Monique"),
  (014,10,"Live and Let Die","Martin, George","If he finds It, Kill Him"),
  (014,11,"Live and Let Die","Martin, George","Trespassers will be eaten"),
  (014,12,"Live and Let Die","Martin, George","Sacrifice"),
  (014,13,"Live and Let Die","Martin, George","Fillet of Soul"),
  (014,14,"Live and Let Die","Martin, George","Snakes Alive"),
  (014,15,"Pet Shop Boys","Pop Miscellaneous","Go West"),
  (014,16,"Pet Shop Boys","Pop Miscellaneous","Shameless"),
  (014,17,"Right Said Fred","Pop Miscellaneous","Stick It Out"),
  (014,18,"Rednex","Pop Miscellaneous","Cotton Eye Joe"),
  (014,19,"Sash!","Pop Miscellaneous","Stay"),
  (014,20,"Sash!","Pop Miscellaneous","Ecuador"),
  (014,21,"Dangermouse","Pop Miscellaneous","Lord of the Bungle"),
  (015,01,"Gobots","Children Miscellaneous","The Weeds of Calcheron"),
  (015,02,"Jimbo","Children Miscellaneous","Trouble at Sea"),
  (015,03,"Action Force","Children Miscellaneous","Return of the Dinosaurs"),
  (015,04,"Masters of the Universe","Children Miscellaneous","The Iron Master"),
  (015,05,"Masters of the Universe","Children Miscellaneous","She-Ra and the Surprise Party"),
  (016,01,"Bugsy Malone","Bugsy Malone","Bugsy Malone"),
  (016,02,"Bugsy Malone","Bugsy Malone","Fat Sams"),
  (016,03,"Bugsy Malone","Bugsy Malone","Tomorrow"),
  (016,04,"Bugsy Malone","Bugsy Malone","We could have been"),
  (016,05,"Bugsy Malone","Bugsy Malone","I'm feeling fine"),
  (016,06,"Bugsy Malone","Bugsy Malone","My Name is Tallulah"),
  (016,07,"Bugsy Malone","Bugsy Malone","So you want to be A Boxer"),
  (016,08,"Bugsy Malone","Bugsy Malone","Only A Fool"),
  (016,09,"Bugsy Malone","Bugsy Malone","Down, Down, Down and Out"),
  (016,10,"Bugsy Malone","Bugsy Malone","We could have been"),
  (016,11,"Total Recall","Total Recall","Title Theme"),
  (016,12,"Disney, Walt","Lion King 2","He lives in You"),
  (016,13,"Disney, Walt","Lion King 2","We are One"),
  (016,14,"Disney, Walt","Lion King 2","My Little Kovu"),
  (016,15,"Disney, Walt","Lion King 2","In Upende"),
  (016,16,"Disney, Walt","Lion King 2","Exile"),
  (016,17,"Disney, Walt","Lion King 2","Love will find A Way"),
  (016,18,"Disney, Walt","Lion King 2","Lion King 2 Theme"),
  (016,19,"Weber, Andrew L.","Cats","Overture"),
  (016,20,"Weber, Andrew L.","Cats","Jellicle Songs for Jellicle Cats"),
  (016,21,"Weber, Andrew L.","Cats","The Naming of Cats"),
  (016,22,"Weber, Andrew L.","Cats","The Invitation to the Jellicle Ball"),
  (016,23,"Weber, Andrew L.","Cats","The Old Gumbie Cat"),
  (016,24,"Weber, Andrew L.","Cats","The Rum Tum Tigger"),
  (016,25,"Weber, Andrew L.","Cats","Grizabella The Glamour Cat"),
  (016,26,"Weber, Andrew L.","Cats","Bustopher Jones"),
  (016,27,"Weber, Andrew L.","Cats","Mungojerrie and Rumpleteazer"),
  (016,28,"Weber, Andrew L.","Cats","Old Deuteronomy"),
  (016,29,"Weber, Andrew L.","Cats","The Jellicle Ball"),
  (016,30,"Weber, Andrew L.","Cats","Grizabella"),
  (016,31,"Weber, Andrew L.","Cats","Moments of Happiness"),
  (016,32,"Weber, Andrew L.","Cats","Gus The Theatre Cat"),
  (016,33,"Weber, Andrew L.","Cats","Growltiger's Last Stand"),
  (016,34,"Weber, Andrew L.","Cats","Skimbleshanks The Railway Cat"),
  (016,35,"Weber, Andrew L.","Cats","Macavity"),
  (016,36,"Weber, Andrew L.","Cats","Mr. Mistoffolees"),
  (016,37,"Weber, Andrew L.","Cats","Memory"),
  (016,38,"Weber, Andrew L.","Cats","The Journey to the Heaviside Layer"),
  (016,39,"Weber, Andrew L.","Cats","The Ad-dressing of Cats"),
  (017,01,"Bach, Johann S.","J. S. Bach Organ","Prelude E Flat Major"),
  (017,02,"Bach, Johann S.","J. S. Bach Organ","Fugue E Flat Major"),
  (017,03,"Bach, Johann S.","J. S. Bach Organ","Prelude G Major"),
  (017,04,"Bach, Johann S.","J. S. Bach Organ","Fugue G Major"),
  (017,05,"Bach, Johann S.","J. S. Bach Organ","Prelude C Minor"),
  (017,06,"Bach, Johann S.","J. S. Bach Organ","Fugue C Minor"),
  (017,07,"Bach, Johann S.","J. S. Bach Organ","Prelude A Minor"),
  (017,08,"Bach, Johann S.","J. S. Bach Organ","Fugue A Minor"),
  (017,09,"Bach, Johann S.","J. S. Bach Organ","Prelude E Minor"),
  (017,10,"Bach, Johann S.","J. S. Bach Organ","Fugue E Minor"),
  (017,11,"Bach, Johann S.","J. S. Bach Organ","Prelude C Major"),
  (017,12,"Bach, Johann S.","J. S. Bach Organ","Fugue C Major"),
  (018,01,"Bach, Johann S.","J. S. Bach Organ","Prelude B Minor"),
  (018,02,"Bach, Johann S.","J. S. Bach Organ","Fugue B Minor"),
  (018,03,"Bach, Johann S.","J. S. Bach Organ","Prelude F Minor"),
  (018,04,"Bach, Johann S.","J. S. Bach Organ","Fugue F Minor"),
  (018,05,"Bach, Johann S.","J. S. Bach Organ","Toccata D Minor"),
  (018,06,"Bach, Johann S.","J. S. Bach Organ","Fugue D Minor"),
  (018,07,"Bach, Johann S.","J. S. Bach Organ","Toccata C Major"),
  (018,08,"Bach, Johann S.","J. S. Bach Organ","Adagio C Major"),
  (018,09,"Bach, Johann S.","J. S. Bach Organ","Fugue C Major"),
  (018,10,"Bach, Johann S.","J. S. Bach Organ","Passacaglia C Minor"),
  (018,11,"Bach, Johann S.","J. S. Bach Organ","Fugue C Minor"),
  (018,12,"Bach, Johann S.","J. S. Bach Organ","Fantasia G Minor"),
  (018,13,"Bach, Johann S.","J. S. Bach Organ","Fugue G Minor"),
  (019,01,"Franck, Cesar A.","C. Franck Organ","Fantaisie A Major"),
  (019,02,"Franck, Cesar A.","C. Franck Organ","Cantabile"),
  (019,03,"Franck, Cesar A.","C. Franck Organ","Piece Heroique"),
  (019,04,"Franck, Cesar A.","C. Franck Organ","Choral 1 E Major"),
  (019,05,"Franck, Cesar A.","C. Franck Organ","Choral 3 A Minor"),
  (019,06,"Franck, Cesar A.","C. Franck Organ","Andantino G Minor"),
  (020,01,"Boellmann, Leonard","Suite Gothique","Suite Gothique – Introduction"),
  (020,02,"Boellmann, Leonard","Suite Gothique","Suite Gothique – Menuet Gothique"),
  (020,03,"Boellmann, Leonard","Suite Gothique","Suite Gothique – Priere a Notre-Dame"),
  (020,04,"Boellmann, Leonard","Suite Gothique","Suite Gothique – Toccata"),
  (020,05,"Messiaen, Olivier","La Nativite du Seigneur","La Nativite du Seigneur – La Vierge de L'Enfant"),
  (020,06,"Messiaen, Olivier","La Nativite du Seigneur","La Nativite du Seigneur – Les Bergers"),
  (020,07,"Messiaen, Olivier","La Nativite du Seigneur","La Nativite du Seigneur – Desseins Eternels"),
  (020,08,"Messiaen, Olivier","La Nativite du Seigneur","La Nativite du Seigneur – Le Verbe"),
  (020,09,"Messiaen, Olivier","La Nativite du Seigneur","La Nativite du Seigneur – Les Enfants de Dieu"),
  (020,10,"Messiaen, Olivier","La Nativite du Seigneur","La Nativite du Seigneur – Jesus accepte La Souffrance"),
  (020,11,"Messiaen, Olivier","La Nativite du Seigneur","La Nativite du Seigneur – Les Mages"),
  (020,12,"Messiaen, Olivier","La Nativite du Seigneur","La Nativite du Seigneur – Dieu parmi Nous"),
  (021,01,"Franck, Cesar A.","French Organ","Prelude/Fugue/Variation B Minor"),
  (021,02,"Guilmant, Felix A.","French Organ","Sonata 1 D Minor – Introduction/Allegro"),
  (021,03,"Guilmant, Felix A.","French Organ","Sonata 1 D Minor – Pastorale"),
  (021,04,"Guilmant, Felix A.","French Organ","Sonata 1 D Minor – Finale"),
  (021,05,"Jongen, Joseph","French Organ","Chant de May"),
  (021,06,"Guilmant, Felix A.","French Organ","March upon Handel's Lift up Your Heads"),
  (021,07,"Widor, Charles M. J. A.","French Organ","Organ Symphony 5 – Toccata"),
  (021,08,"Reger, Max","German Organ","Toccata 59"),
  (021,09,"Reger, Max","German Organ","Fugue 59"),
  (021,10,"Reger, Max","German Organ","Fantasia on 'Straf' mich nicht in deinem Zorn'"),
  (022,01,"Reubke, Julius","German Organ","Sonata 'The 94th Psalm'"),
  (022,02,"Bach, Johann S.","German Organ","Variations on 'Sei Gegruesset, Jesu Guetig'"),
  (022,03,"Bach, Johann S.","German Organ","Fugue G Major"),
  (022,04,"Bach, Johann S.","German Organ","Toccata F Major"),
  (022,05,"Bach, Johann S.","German Organ","Fugue F Major"),
  (022,06,"Muffat, Georg","German Organ","Toccata 1"),
  (022,07,"Muffat, Georg","German Organ","Toccata 3"),
  (023,01,"Muffat, Georg","German Organ","Toccata 8"),
  (023,02,"Muffat, Georg","German Organ","Toccata 11"),
  (023,03,"Muffat, Georg","German Organ","Toccata 12"),
  (023,04,"Muffat, Georg","German Organ","Passacaglia G Minor"),
  (023,05,"Muffat, Georg","German Organ","Chaconne G Major"),
  (023,06,"Siegried Music Box","Music Box","Voh Himmel hoch, da komm ich her"),
  (023,07,"Siegried Music Box","Music Box","Es ist ein Reis entsprungen"),
  (023,08,"Siegried Music Box","Music Box","Stille Nacht"),
  (023,09,"Siegried Music Box","Music Box","Ihr Hirten erwacht"),
  (023,10,"Siegried Music Box","Music Box","O du froehliche"),
  (023,11,"Siegried Music Box","Music Box","Ihr Kinderlein kommet"),
  (023,12,"Siegried Music Box","Music Box","Am Weihnachtsbaume die Lichter brennen"),
  (023,13,"Siegried Music Box","Music Box","Kling Gloeckchen kling"),
  (023,14,"Siegried Music Box","Music Box","O Tannenbaum"),
  (023,15,"Siegried Music Box","Music Box","Heiligste Nacht"),
  (023,16,"Siegried Music Box","Music Box","Dies ist der Tag, den Gott gemacht"),
  (024,01,"Strauss, Johann","Koksijde Organ","Waltz Pot Pourri"),
  (024,02,"Latann","Koksijde Organ","Freeway"),
  (024,03,"Mariotti","Koksijde Organ","Mary Lou"),
  (024,04,"Denys, O.","Koksijde Organ","Return to Baden-Baden"),
  (024,05,"Stock, E. van der","Koksijde Organ","Joyful Trumpets"),
  (024,06,"Cogge, H.","Koksijde Organ","150 Jaar Leisele"),
  (024,07,"Waldteufel, Emil","Koksijde Organ","The Skaters"),
  (024,08,"Hamel, G.","Koksijde Organ","Crystal Pearls"),
  (024,09,"Leadbetter, H.","Koksijde Organ","Goodnight Irene"),
  (024,10,"Stenz, H.","Koksijde Organ","Hoor de Muzikanten"),
  (024,11,"Winkler","Koksijde Organ","Starry Night"),
  (024,12,"Busterman, J.","Koksijde Organ","Where is Loesje"),
  (024,13,"Craming, S.","Koksijde Organ","On the North Sea Beach"),
  (024,14,"Caerts, L.","Koksijde Organ","Long Live Spain"),
  (024,15,"Various","Koksijde Organ","Pot Pourri"),
  (024,16,"Bach, Johann S.","Switched On Bach 1","Sinfonia from Cantata 29"),
  (024,17,"Bach, Johann S.","Switched On Bach 1","Air on the G String"),
  (024,18,"Bach, Johann S.","Switched On Bach 1","Two-Part Invention F Major"),
  (024,19,"Bach, Johann S.","Switched On Bach 1","Two-Part Invention B Flat Major"),
  (024,20,"Bach, Johann S.","Switched On Bach 1","Two-part Invention D Minor"),
  (024,21,"Bach, Johann S.","Switched On Bach 1","Jesu, Joy of Man's Desiring"),
  (024,22,"Bach, Johann S.","Switched On Bach 1","Prelude E Flat major"),
  (024,23,"Bach, Johann S.","Switched On Bach 1","Fugue E Flat Major"),
  (024,24,"Bach, Johann S.","Switched On Bach 1","Brandenburg Concerto 3 Movement 1"),
  (024,25,"Bach, Johann S.","Switched On Bach 1","Brandenburg Concerto 3 Movement 2"),
  (024,26,"Bach, Johann S.","Switched On Bach 1","Brandenburg Concerto 3 Movement 3"),
  (025,01,"Bach, Johann S.","Switched On Bach 1","Prelude C Minor"),
  (025,02,"Bach, Johann S.","Switched On Bach 1","Fugue C Minor"),
  (025,03,"Bach, Johann S.","Switched On Bach 1","Chorale 'Wachet Auf'"),
  (025,04,"Bach, Johann S.","Switched On Bach 2","Suite 2 Badinerie"),
  (025,05,"Bach, Johann S.","Switched On Bach 2","Suite 2 Minuet"),
  (025,06,"Bach, Johann S.","Switched On Bach 2","Suite 2 Bourree"),
  (025,07,"Bach, Johann S.","Switched On Bach 2","Two-Part Invention A Minor"),
  (025,08,"Bach, Johann S.","Switched On Bach 2","Two-Part Invention A Major"),
  (025,09,"Bach, Johann S.","Switched On Bach 2","Cantata 208 'Sheep may safely graze'"),
  (025,10,"Bach, Johann S.","Switched On Bach 2","Musette D Major"),
  (025,11,"Bach, Johann S.","Switched On Bach 2","Minuet G Major"),
  (025,12,"Bach, Johann S.","Switched On Bach 2","Bist du bei mir"),
  (025,13,"Bach, Johann S.","Switched On Bach 2","Marche D Major"),
  (025,14,"Bach, Johann S.","Switched On Bach 2","Brandenburg 5 Movement 1"),
  (025,15,"Bach, Johann S.","Switched On Bach 2","Brandenburg 5 Movement 2"),
  (025,16,"Bach, Johann S.","Switched On Bach 2","Brandenburg 5 Movement 3"),
  (025,17,"Monteverdi, Claudio G. A.","Well-Tempered Synthesiser","Orfeo Suite"),
  (025,18,"Scarlatti, Alessandro","Well-Tempered Synthesiser","Sonata G Major"),
  (025,19,"Scarlatti, Alessandro","Well-Tempered Synthesiser","Sonata D Major"),
  (025,20,"Scarlatti, Alessandro","Well-Tempered Synthesiser","Sonata E Major"),
  (025,21,"Scarlatti, Alessandro","Well-Tempered Synthesiser","Sonata D Major"),
  (025,22,"Handel, George F.","Well-Tempered Synthesiser","Water Music – Bourree"),
  (025,23,"Handel, George F.","Well-Tempered Synthesiser","Water Music – Air"),
  (025,24,"Handel, George F.","Well-Tempered Synthesiser","Water Music – Allegro Deciso"),
  (025,25,"Monteverdi, Claudio G. A.","Well-Tempered Synthesiser","Domine ad Adjuvandum"),
  (026,01,"Bach, Johann S.","Well-Tempered Synthesiser","Brandenburg 4 Movement 1"),
  (026,02,"Bach, Johann S.","Well-Tempered Synthesiser","Brandenburg 4 Movement 2"),
  (026,03,"Bach, Johann S.","Well-Tempered Synthesiser","Brandenburg 4 Movement 3"),
  (026,04,"Carlos, Walter","Clockwork Orange","Timesteps"),
  (026,05,"Beethoven, Ludwig van","Clockwork Orange","Symphony 9 Movement 4"),
  (026,06,"Purcell, Henry","Clockwork Orange","Music for the Funeral of Queen Mary"),
  (026,07,"Rossini, Gioacchino A.","Clockwork Orange","The Thieving Magpie"),
  (026,08,"Carlos, Walter/Elkind, Rachel","Clockwork Orange","Clockwork Orange Main Theme"),
  (026,09,"Beethoven, Ludwig van","Clockwork Orange","Symphony 9 Movement 2"),
  (026,10,"Rossini, Gioacchino A.","Clockwork Orange","William Tell Overture"),
  (026,11,"Carlos, Walter/Elkind, Rachel","Clockwork Orange","Country Lane"),
  (026,12,"Decca","Frequency Test Record","50 Hz -17.5 dB"),
  (026,13,"Decca","Frequency Test Record","100 Hz -12.7 dB"),
  (026,14,"Decca","Frequency Test Record","250 Hz -5.8 dB"),
  (026,15,"Decca","Frequency Test Record","500 Hz -1.9 dB"),
  (026,16,"Decca","Frequency Test Record","1 kHz 0.0 dB"),
  (026,17,"Decca","Frequency Test Record","2 kHz +2.3 dB"),
  (026,18,"Decca","Frequency Test Record","3 kHz +4.3 dB"),
  (026,19,"Decca","Frequency Test Record","4 kHz +7.3 dB"),
  (026,20,"Decca","Frequency Test Record","5 kHz +8.0 dB"),
  (026,21,"Decca","Frequency Test Record","6 kHz +9.7 dB"),
  (026,22,"Decca","Frequency Test Record","7 kHz +10.8 dB"),
  (026,23,"Decca","Frequency Test Record","8 kHz +12.4 dB"),
  (026,24,"Decca","Frequency Test Record","8 kHz +12.7 dB"),
  (026,25,"Decca","Frequency Test Record","10 kHz +13.1 dB"),
  (026,26,"Deutsche Grammophon","Stereo Test Record","Channel Balance"),
  (026,27,"Deutsche Grammophon","Stereo Test Record","Channel Tone"),
  (026,28,"Deutsche Grammophon","Stereo Test Record","Loudspeaker Phase"),
  (026,29,"Deutsche Grammophon","Stereo Test Record","Sound Effects"),
  (026,30,"Donaldson","Stereo Test Record","My Blue Heaven"),
  (027,01,"Clark, Louis","Hooked on Classics 1","Hooked on Classics 1/2"),
  (027,02,"Clark, Louis","Hooked on Classics 1","Hooked on Romance 1"),
  (027,03,"Clark, Louis","Hooked on Classics 1","Hooked on Classics 3"),
  (027,04,"Clark, Louis","Hooked on Classics 1","Hooked on Bach"),
  (027,05,"Clark, Louis","Hooked on Classics 1","Hooked on Tchaikovsky"),
  (027,06,"Clark, Louis","Hooked on Classics 1","Hooked on A Song"),
  (027,07,"Clark, Louis","Hooked on Classics 1","Hooked on Mozart"),
  (027,08,"Clark, Louis","Hooked on Classics 1","Hooked on Mendelssohn"),
  (027,09,"Clark, Louis","Hooked on Classics 1","Hooked on A Can-Can"),
  (027,10,"Clark, Louis","Hooked on Classics 2","Can't stop the Classics 1"),
  (027,11,"Clark, Louis","Hooked on Classics 2","Hooked on America"),
  (027,12,"Clark, Louis","Hooked on Classics 2","Hooked on Romance 2"),
  (027,13,"Clark, Louis","Hooked on Classics 2","Can't stop the Classics 2"),
  (028,01,"Clark, Louis","Hooked on Classics 2","A Night at the Opera"),
  (028,02,"Clark, Louis","Hooked on Classics 2","Tales of the Vienna Waltz"),
  (028,03,"Clark, Louis","Hooked on Classics 2","Hooked on Baroque"),
  (028,04,"Clark, Louis","Hooked on Classics 2","If you knew Sousa"),
  (028,05,"Clark, Louis","Hooked on Classics 2","If you knew Sousa (and Friends)"),
  (028,06,"Rondo Veneziano","Rondo Veneziano","La Serenissima"),
  (028,07,"Rondo Veneziano","Rondo Veneziano","Rialto"),
  (028,08,"Rondo Veneziano","Rondo Veneziano","Canale grande"),
  (028,09,"Rondo Veneziano","Rondo Veneziano","Aria di Festa"),
  (028,10,"Rondo Veneziano","Rondo Veneziano","Sinfonia per un Addio"),
  (028,11,"Rondo Veneziano","Rondo Veneziano","Arlecchino"),
  (028,12,"Rondo Veneziano","Rondo Veneziano","Regata dei Dogi"),
  (028,13,"Rondo Veneziano","Rondo Veneziano","Notturno in Gondola"),
  (028,14,"Rondo Veneziano","Rondo Veneziano","Capriccio Veneziano"),
  (028,15,"Rondo Veneziano","Rondo Veneziano","Magico Incontro"),
  (028,16,"Barry, John","Black Hole","Overture"),
  (028,17,"Barry, John","Black Hole","Main Title"),
  (028,18,"Barry, John","Black Hole","The Door Opens"),
  (028,19,"Barry, John","Black Hole","Zero gravity"),
  (028,20,"Barry, John","Black Hole","Six Robots"),
  (029,01,"Barry, John","Black Hole","Durant is Dead"),
  (029,02,"Barry, John","Black Hole","Start the Countdown"),
  (029,03,"Barry, John","Black Hole","Laser"),
  (029,04,"Barry, John","Black Hole","Into the Hole"),
  (029,05,"Barry, John","Black Hole","End Title"),
  (029,06,"Khatchaturian, Aram I.","Symphonic Dances","Sabre Dance"),
  (029,07,"Brahms, Johannes","Symphonic Dances","Hungarian Dance 5"),
  (029,08,"Provenzano","Symphonic Dances","Bolero"),
  (029,09,"Falla, Manuel de","Symphonic Dances","Ritual Fire Dance"),
  (029,10,"Borodin, Alexander P.","Symphonic Dances","Polovetsian Dances"),
  (029,11,"Provenza","Symphonic Dances","Gypsy Wedding Czaidas"),
  (029,12,"Rimsky-Korsakov, Nikolay A.","Symphonic Dances","Dance of the Tumblers"),
  (029,13,"Liszt, Franz","Glorious Melodies","Liebestraum"),
  (029,14,"MacDowell","Glorious Melodies","To a Wild Rose"),
  (029,15,"Dvorak, Antonin","Glorious Melodies","Humoresque 7"),
  (029,16,"Handel, George F.","Glorious Melodies","Minuet from 'Berenice'"),
  (029,17,"Traditional","Glorious Melodies","Greensleeves"),
  (029,18,"Boccherini, Luigi","Glorious Melodies","Minuet"),
  (030,01,"Bizet, Georges","Glorious Melodies","Agnus Dei"),
  (030,02,"Bach, Johann S.","Glorious Melodies","Air on the G String"),
  (030,03,"Handel, George F.","Glorious Melodies","Large from 'Serse'"),
  (030,04,"Bach, Johann S.","Glorious Melodies","Jesu, Joy of Man's Desiring"),
  (030,05,"Schubert, Franz P.","Glorious Melodies","Ave Maria"),
  (030,06,"Sullivan, Arthur S.","Glorious Melodies","The Lost Chord"),
  (030,07,"Bach, Johann S.","James Galway","Minuet/Badinerie Suite 2"),
  (030,08,"Debussy, Claude A.","James Galway","Claire de Lune"),
  (030,09,"Debussy, Claude A.","James Galway","Syrinx"),
  (030,10,"Debussy, Claude A.","James Galway","The Little Shepherd"),
  (030,11,"Paganini, Niccoli","James Galway","Moto Perpetuo"),
  (030,12,"Vivaldi, Antonio","James Galway","Flute Concerto G Minor"),
  (030,13,"Gluck, Christoph W.","James Galway","Dance of the Blessed Spirits"),
  (030,14,"Berkeley, L.","James Galway","Sonatina"),
  (030,15,"Mozart, Wolfgang A.","James Galway","Andante C Major"),
  (031,01,"Landino, F.","Medieval Harp","Angelica Belta"),
  (031,02,"Anonymous","Medieval Harp","Danse Royale"),
  (031,03,"Anonymous","Medieval Harp","In Saeculum Viellatoris"),
  (031,04,"Anonymous","Medieval Harp","Lamento di Tristano"),
  (031,05,"Anonymous","Medieval Harp","Ductia"),
  (031,06,"Anonymous","Medieval Harp","Veri Floris sub Figura"),
  (031,07,"Anonymous","Medieval Harp","Clausolae"),
  (031,08,"Anonymous","Medieval Harp","Saltarello"),
  (031,09,"Legrant, J.","Medieval Harp","Entre Vous Nouveaux Maries"),
  (031,10,"Gervaise, Claude","Medieval Harp","Danceries"),
  (031,11,"Isaac, H.","Celtic Harp","Carmen Saecularis"),
  (031,12,"Sermisy, C. de","Celtic Harp","Puisqu'en Amour"),
  (031,13,"Brihuega","Celtic Harp","Villancico"),
  (031,14,"Galilei, Vicenzo","Celtic Harp","Saltarello"),
  (031,15,"Anonymous","Celtic Harp","In Saeculum Artifex"),
  (031,16,"Vogelweide, W. von der","Celtic Harp","Palestinalied"),
  (031,17,"Anonymous","Celtic Harp","Trotto"),
  (031,18,"Obrecht, Jacob","Celtic Harp","Ricercare"),
  (031,19,"Monachus, G.","Celtic Harp","Gymel"),
  (031,20,"Anonymous","Celtic Harp","Estampie Royale"),
  (031,21,"Anonymous","Celtic Harp","La Manfredina"),
  (031,22,"Ghiezeghem, H. van","Celtic Harp","Gentil Gallans"),
  (031,23,"Attaignant, Pierre","Celtic Harp","Tabulatura"),
  (031,24,"Brumel, Antoine","Celtic Harp","Vray Dieu d'Amours"),
  (031,25,"Gervaise, Claude","Celtic Harp","Danceries"),
  (031,26,"Gastoldi, Giovanni G.","Celtic Harp","Bicinium"),
  (031,27,"Stivell, Alain","Celtic Harp","Ys"),
  (031,28,"Megevand, D.","Celtic Harp","Marv Pontkalleg"),
  (031,29,"Dolmetsch, Arnold","Celtic Harp","Ap Huw Penllyn"),
  (031,30,"Stivell, Alain","Celtic Harp","Eliz Isa"),
  (031,31,"Stivell, Alain","Celtic Harp","Gaeltacht"),
  (032,01,"Anonymous","Non-Stop Dancing 1600","Schiarazula Marazula"),
  (032,02,"Anonymous","Non-Stop Dancing 1600","Courante"),
  (032,03,"Anonymous","Non-Stop Dancing 1600","Volte"),
  (032,04,"Anonymous","Non-Stop Dancing 1600","Courante"),
  (032,05,"Anonymous","Non-Stop Dancing 1600","Volte"),
  (032,06,"Anonymous","Non-Stop Dancing 1600","Istampita Ghaetta"),
  (032,07,"Anonymous","Non-Stop Dancing 1600","Saltarello"),
  (032,08,"Hupfauff","Non-Stop Dancing 1600","Welscher Tanz"),
  (032,09,"Anonymous","Non-Stop Dancing 1600","Calata ala Spagnola"),
  (032,10,"Anonymous","Non-Stop Dancing 1600","Basse Danse La Magdalena"),
  (032,11,"Rotta","Non-Stop Dancing 1600","Lamento di Tristano"),
  (032,12,"Anonymous","Non-Stop Dancing 1600","Branle de Bourgogne"),
  (032,13,"Anonymous","Non-Stop Dancing 1600","Ungarescha Saltarello"),
  (032,14,"Anonymous","Non-Stop Dancing 1600","Ronde"),
  (032,15,"Schein, Johann H.","Non-Stop Dancing 1600","Allemande Tripla"),
  (032,16,"Anonymous","Non-Stop Dancing 1600","Tantz"),
  (032,17,"Anonymous","Non-Stop Dancing 1600","Galliard"),
  (032,18,"Anonymous","Non-Stop Dancing 1600","Catkanei"),
  (032,19,"Anonymous","Non-Stop Dancing 1600","Branle de Bourgogne"),
  (032,20,"Anonymous","Non-Stop Dancing 1600","Branle de Champagne"),
  (032,21,"Anonymous","Non-Stop Dancing 1600","Reprise/Galliard"),
  (032,22,"Praetorius, Michael","Non-Stop Dancing 1600","Gavotte"),
  (032,23,"Praetorius, Michael","Non-Stop Dancing 1600","Spagnoletta"),
  (032,24,"Praetorius, Michael","Non-Stop Dancing 1600","La Bouree"),
  (032,25,"Widmann","Non-Stop Dancing 1600","Magdalena"),
  (032,26,"Widmann","Non-Stop Dancing 1600","Agatha"),
  (032,27,"Widmann","Non-Stop Dancing 1600","Regina"),
  (032,28,"Anonymous","Non-Stop Dancing 1600","Tanz im Aicholdinger Schloss"),
  (032,29,"Anonymous","Non-Stop Dancing 1600","Eichstatter Hofmuehltanz"),
  (032,30,"Anonymous","Non-Stop Dancing 1600","Riedenburger Tanz"),
  (032,31,"Anonymous","Non-Stop Dancing 1600","Anonym"),
  (032,32,"Anonymous","Non-Stop Dancing 1600","Pavan"),
  (032,33,"Anonymous","Non-Stop Dancing 1600","Baletto"),
  (032,34,"Anonymous","Non-Stop Dancing 1600","Galliarde de Monsieur Wustron"),
  (032,35,"Anonymous","Non-Stop Dancing 1600","Galliarde de la Guerre"),
  (032,36,"Anonymous","Non-Stop Dancing 1600","Reprise"),
  (032,37,"Praetorius, Michael","Terpsichore","Introduction/Courante"),
  (032,38,"Praetorius, Michael","Terpsichore","Ballet"),
  (032,39,"Praetorius, Michael","Terpsichore","Hahnentanz"),
  (032,40,"Praetorius, Michael","Terpsichore","Tanz der Fischer/Bueerinnen"),
  (032,41,"Praetorius, Michael","Terpsichore","Fastnachtstanz/Feuertanz"),
  (032,42,"Praetorius, Michael","Terpsichore","Gavottes"),
  (032,43,"Praetorius, Michael","Terpsichore","Spagnoletta/Bouree"),
  (033,01,"Holborne, Antony","Short Airs","Wanton"),
  (033,02,"Holborne, Antony","Short Airs","Nowel's Galliard"),
  (033,03,"Holborne, Antony","Short Airs","Heigh-Ho Holiday"),
  (033,04,"Holborne, Antony","Short Airs","The Choise"),
  (033,05,"Holborne, Antony","Short Airs","As it fell upon a Holy Eve"),
  (033,06,"Holborne, Antony","Short Airs","The Fairie-Round"),
  (033,07,"Holborne, Antony","Short Airs","Last Will and Testament"),
  (033,08,"Holborne, Antony","Short Airs","The Honie-Suckle"),
  (033,09,"Holborne, Antony","Short Airs","The Marie-Gold"),
  (033,10,"Holborne, Antony","Short Airs","The New-Yeeres Gift"),
  (033,11,"Holborne, Antony","Short Airs","The Night Watch"),
  (033,12,"Lambranzi, Giovanni","Lambranzi Dances","First Sequence"),
  (033,13,"Lambranzi, Giovanni","Lambranzi Dances","Second Sequence"),
  (033,14,"Lambranzi, Giovanni","Lambranzi Dances","Third Sequence"),
  (033,15,"Templeton, Alex","Bach goes to Town","Bach goes to Town"),
  (033,16,"Malcolm, George","Back before The Mast","Back before The Mast"),
  (033,17,"Paradies, Domenico","Toccata","Toccata"),
  (033,18,"Daquin, Louis C.","The Cuckoo","The Cuckoo"),
  (033,19,"Rimsky-Korsakov, Nikolay A.","The Flight of The Bumble Bee","The Flight of The Bumble Bee"),
  (033,20,"Romberg","Student Prince","Drink, Drink, Drink"),
  (033,21,"Romberg","Student Prince","Gaudeamus igitur"),
  (033,22,"Ketelbey","In A Monastery Garden","In A Monastery Garden"),
  (033,23,"Ketelbey","In A Persian Market","In A Persian Market"),
  (033,24,"Galliard, Johann E.","Galliard Suite 1","Suite 1 Allegro Assai"),
  (033,25,"Galliard, Johann E.","Galliard Suite 1","Suite 1 Hornpipe"),
  (033,26,"Galliard, Johann E.","Galliard Suite 2","Suite 2 Siciliano"),
  (033,27,"Galliard, Johann E.","Galliard Suite 2","Suite 2 Allegro"),
  (033,28,"Senaille, Jean","Allegro Spiritoso","Allegro Spiritoso"),
  (033,29,"Traiditonal","Lamento di Tristan","Lamento di Tristan"),
  (033,30,"Tcherepine, N. N.","Esquisse","Esquisse"),
  (033,31,"Sullivan, Arthur S.","The Mikado","Behold The Lord High Executioner"),
  (033,32,"Sullivan, Arthur S.","The Mikado","A Wand'ring Minstrel I"),
  (033,33,"Sullivan, Arthur S.","The Mikado","Brightly dawns Our Wedding Day"),
  (033,34,"Sullivan, Arthur S.","The Mikado","Tit Willow"),
  (034,01,"Xylouris, N.","Greek Folk","Dirlada"),
  (034,02,"Galani, D.","Greek Folk","Maria in Yellow"),
  (034,03,"Emmanouel, C.","Greek Folk","The Mermaid"),
  (034,04,"Hadjidakis-Gatsos, H.","Greek Folk","Speak to Me"),
  (034,05,"Marselos, C.","Greek Folk","Sergeant Stamoulis"),
  (034,06,"Gray, K./Tsitsanis, V.","Greek Folk","For the Eyes of Love"),
  (034,07,"Hadjidakis, A./ Hadjidakis, E.","Greek Folk","The Bratsera Boat"),
  (034,08,"Papaioannou, Y.","Greek Folk","Solo Bouzouki"),
  (034,09,"Athenaei, I.","Greek Folk","Athens"),
  (034,10,"Emmanouel, C.","Greek Folk","George's Wife"),
  (034,11,"Nikolaou, L.","Greek Folk","White, Red, Yellow, Blue"),
  (034,12,"Xarhakos-Papadopoulos","Greek Folk","Cruel Life"),
  (034,13,"Karandi, M.","Greek Folk","We argued"),
  (034,14,"Leferis, Y.","Greek Folk","My Fairy Tale"),
  (034,15,"Hadjidakis, S.","Greek Folk","The Little Sea"),
  (034,16,"Hadjidakis-Gatsos, H.","Greek Folk","The Children of Piraeus"),
  (034,17,"Zamfir, Gheorghi","Roumanian Folk","Sirba Lui Pompieru/Am O Mindra Mititica"),
  (034,18,"Zamfir, Gheorghi","Roumanian Folk","Breaza de la Dragodana"),
  (034,19,"Zamfir, Gheorghi","Roumanian Folk","Muntilor cu Brazi Inalti/Ferice Codre de Tine"),
  (034,20,"Zamfir, Gheorghi","Roumanian Folk","Briul de La Faget"),
  (034,21,"Zamfir, Gheorghi","Roumanian Folk","Sirba de La Gaiesti"),
  (034,22,"Zamfir, Gheorghi","Roumanian Folk","Suie de Sirbe Oltenesti"),
  (034,23,"Zamfir, Gheorghi","Roumanian Folk","Sapte Vai Si-o Vale-Adinca"),
  (035,01,"Zamfir, Gheorghi","Roumanian Folk","Invirtita"),
  (035,02,"Zamfir, Gheorghi","Roumanian Folk","Asta e Poteca Mea"),
  (035,03,"Zamfir, Gheorghi","Roumanian Folk","Joc de Doi"),
  (035,04,"Rapsodia Romana","Roumanian Folk","Jocuri Muntenesti"),
  (035,05,"Rapsodia Romana","Roumanian Folk","Sirba Munteneasca"),
  (035,06,"Rapsodia Romana","Roumanian Folk","Cintec de Dragoste/Hora"),
  (035,07,"Rapsodia Romana","Roumanian Folk","Ca din Caval"),
  (035,08,"Rapsodia Romana","Roumanian Folk","Geampara"),
  (035,09,"Rapsodia Romana","Roumanian Folk","Doina Oltului"),
  (035,10,"Rapsodia Romana","Roumanian Folk","Geampara"),
  (035,11,"Rapsodia Romana","Roumanian Folk","Hora Munteneasca"),
  (035,12,"Rapsodia Romana","Roumanian Folk","Briu Oltenesc"),
  (035,13,"Rapsodia Romana","Roumanian Folk","Doina/Joc de Doi"),
  (035,14,"Rapsodia Romana","Roumanian Folk","Balada/Hora"),
  (035,15,"Rapsodia Romana","Roumanian Folk","Sirba din Bailesti"),
  (035,16,"Rapsodia Romana","Roumanian Folk","De-a Lungul si Hategana"),
  (035,17,"Rapsodia Romana","Roumanian Folk","Sirba de La Goicea"),
  (035,18,"Rapsodia Romana","Roumanian Folk","Joc Moldovenesc"),
  (035,19,"Rapsodia Romana","Roumanian Folk","Sirba"),
  (035,20,"Paraschiv Oprea","Roumanian Folk","Toconolele"),
  (035,21,"Paraschiv Oprea","Roumanian Folk","Scaloianul"),
  (035,22,"Paraschiv Oprea","Roumanian Folk","Paparuda"),
  (035,23,"Paraschiv Oprea","Roumanian Folk","Brezaia Munteneasca"),
  (035,24,"Paraschiv Oprea","Roumanian Folk","Dragaica/Hora Dragaicii"),
  (035,25,"Paraschiv Oprea","Roumanian Folk","Sorcova, Vesela"),
  (035,26,"Paraschiv Oprea","Roumanian Folk","Plugusorul"),
  (035,27,"Paraschiv Oprea","Roumanian Folk","Sus in Deal La Noua Meri"),
  (035,28,"Paraschiv Oprea","Roumanian Folk","Din Cea Zori, Din Cea Gradina"),
  (035,29,"Paraschiv Oprea","Roumanian Folk","Lazarul/Dansul Flacailor"),
  (035,30,"Paraschiv Oprea","Roumanian Folk","Pe Muntii de Piatra"),
  (035,31,"Paraschiv Oprea","Roumanian Folk","Calusul"),
  (036,01,"Lehrer, Tom","An Evening with Tom Lehrer","Poisoning Pigeons in the Park"),
  (036,02,"Lehrer, Tom","An Evening with Tom Lehrer","Bright College Days"),
  (036,03,"Lehrer, Tom","An Evening with Tom Lehrer","A Christmas Carol"),
  (036,04,"Lehrer, Tom","An Evening with Tom Lehrer","The Elements"),
  (036,05,"Lehrer, Tom","An Evening with Tom Lehrer","Oedipus Rex"),
  (036,06,"Lehrer, Tom","An Evening with Tom Lehrer","In Old Mexico"),
  (036,07,"Lehrer, Tom","An Evening with Tom Lehrer","Clementine"),
  (036,08,"Lehrer, Tom","An Evening with Tom Lehrer","It makes a Fellow Proud to be A Soldier"),
  (036,09,"Lehrer, Tom","An Evening with Tom Lehrer","She's My Girl"),
  (036,10,"Lehrer, Tom","An Evening with Tom Lehrer","The Masochism Tango"),
  (036,11,"Lehrer, Tom","An Evening with Tom Lehrer","We will All go together when We go"),
  (036,12,"Lehrer, Tom","Tom Lehrer Revisited","Introduction"),
  (036,13,"Lehrer, Tom","Tom Lehrer Revisited","I wanna go back to Dixie"),
  (036,14,"Lehrer, Tom","Tom Lehrer Revisited","The Wild West is where I want to be"),
  (036,15,"Lehrer, Tom","Tom Lehrer Revisited","The Old Dope Peddler"),
  (036,16,"Lehrer, Tom","Tom Lehrer Revisited","Fight fiercely, Harvard"),
  (036,17,"Lehrer, Tom","Tom Lehrer Revisited","Lobachevksky"),
  (036,18,"Lehrer, Tom","Tom Lehrer Revisited","The Irish Ballad"),
  (036,19,"Lehrer, Tom","Tom Lehrer Revisited","The Hunting Song"),
  (036,20,"Lehrer, Tom","Tom Lehrer Revisited","My Home Town"),
  (036,21,"Lehrer, Tom","Tom Lehrer Revisited","When You are Old and Grey"),
  (037,01,"Lehrer, Tom","Tom Lehrer Revisited","The Wiener Schnitzel Waltz"),
  (037,02,"Lehrer, Tom","Tom Lehrer Revisited","I hold Your Hand in Mine"),
  (037,03,"Lehrer, Tom","Tom Lehrer Revisited","Be prepared"),
  (037,04,"Russell, Anna","Anna Russell","The Ring of the Nibelungs"),
  (037,05,"Russell, Anna","Anna Russell","Introduction to The Concert"),
  (037,06,"Russell, Anna","Anna Russell","How to write your own G&S Opera"),
  (037,07,"Hoffnung, Gerard","Hoffnung Music Festival","Announcement"),
  (037,08,"Hoffnung, Gerard","Hoffnung Music Festival","Fanfare"),
  (037,09,"Hoffnung, Gerard","Hoffnung Music Festival","A Grand Grand Overture"),
  (037,10,"Hoffnung, Gerard","Hoffnung Music Festival","Concerto for Hose-Pipe and Strings"),
  (037,11,"Hoffnung, Gerard","Hoffnung Music Festival","Concerto Popolare"),
  (038,01,"Hoffnung, Gerard","Hoffnung Music Festival","Symphony 94"),
  (038,02,"Hoffnung, Gerard","Hoffnung Music Festival","Speech"),
  (038,03,"Hoffnung, Gerard","Hoffnung Music Festival","Mazurka 47"),
  (038,04,"Hoffnung, Gerard","Hoffnung Music Festival","Lochinvar"),
  (038,05,"Hoffnung, Gerard","Hoffnung Music Festival","Variations on 'Annie Laurie'"),
  (038,06,"Hoffnung, Gerard","Hoffnung Music Festival","Introductory Music"),
  (038,07,"Hoffnung, Gerard","Hoffnung Music Festival","Hoffnung Festival Overture"),
  (038,08,"Hoffnung, Gerard","Hoffnung Music Festival","Metamorphosis on a Bed-Time Theme"),
  (038,09,"Hoffnung, Gerard","Hoffnung Music Festival","Sugar Plums"),
  (038,10,"Hoffnung, Gerard","Hoffnung Music Festival","The Famous Tay Whale"),
  (038,11,"Hoffnung, Gerard","Hoffnung Music Festival","Concerto for Conductor and Orchestra"),
  (038,12,"Hoffnung, Gerard","Hoffnung Music Festival","Punkt Contrapunkt"),
  (038,13,"Hoffnung, Gerard","Hoffnung Music Festival","The United Nations"),
  (038,14,"Hoffnung, Gerard","Hoffnung Music Festival","Waltz for Restriced Orchestra"),
  (038,15,"Hoffnung, Gerard","Hoffnung Music Festival","Introductory Music"),
  (038,16,"Hoffnung, Gerard","Hoffnung Music Festival","Festival Anthem"),
  (038,17,"Hoffnung, Gerard","Hoffnung Music Festival","Leonora Overture"),
  (039,01,"Hoffnung, Gerard","Hoffnung Music Festival","Let's fake an Opera"),
  (039,02,"Hoffnung, Gerard","Hoffnung Music Festival","The Barber of Darmstadt"),
  (039,03,"Hoffnung, Gerard","Hoffnung Music Festival","Ballad of County Down"),
  (039,04,"Hoffnung, Gerard","Hoffnung Music Festival","Belshazzar's Feast"),
  (039,05,"Hoffnung, Gerard","Hoffnung Music Festival","Horrortorio"),
  (039,06,"Hoffnung, Gerard","Hoffnung Music Festival","Mobile for Seven Orchestras"),
  (039,07,"Lewin-richter, Andres","Study 1","Study 1"),
  (039,08,"Mimaroglu, Ilhan","Le Tombeau d'Edgar Poe","Le Tombeau d'Edgar Poe"),
  (039,09,"Mimaroglu, Ilhan","Intermezzo","Intermezzo"),
  (039,10,"Mimaroglu, Ilhan","Bowery Bum","Bowery Bum"),
  (039,11,"Avni, Tzvi","Vocalise","Vocalise"),
  (040,01,"Bach, Johann S.","Bach and His Time","Chorus 1 Christmas Oratorio"),
  (040,02,"Bach, Johann S.","Bach and His Time","Air Suite 3"),
  (040,03,"Bach, Johann S.","Bach and His Time","Allegro Violin Concerto 1"),
  (040,04,"Telemann, Georg P.","Bach and His Time","Recitative/Aria from 'Ino'"),
  (040,05,"Frederick the Great","Bach and His Time","Sinfonia D Major"),
  (040,06,"Vivaldi, Antonio","Bach and His Time","Concerto for Cello C Minor"),
  (040,07,"Gabrieli, Giovanni","Music for A Baroque Festival","Canzon VIII"),
  (040,08,"Rameau, Jean-Philippe","Music for A Baroque Festival","Concert 3 'Les Indes Galantes'"),
  (040,09,"Bach, Johann S.","Music for A Baroque Festival","Harpsichord Concerto 5"),
  (041,01,"Telemann, Georg P.","Music for A Baroque Festival","Trumpet Concerto D Major"),
  (041,02,"Handel, George F.","Music for A Baroque Festival","Zadok the Priest"),
  (041,03,"Vivaldi, Antonio","Baroque Flute Concertos","Piccolo Concerto C Major"),
  (041,04,"Pergolesi, Giovanni B.","Baroque Flute Concertos","Flute Concerto G Major"),
  (041,05,"Leclair, Jean-Marie","Baroque Flute Concertos","Flute Concerto C Major"),
  (041,06,"Woodcock, R. T.","Baroque Flute Concertos","Flute Concerto E Minor"),
  (042,01,"Beethoven, Ludwig van","Symphony 1 C Major","Movement 1"),
  (042,02,"Beethoven, Ludwig van","Symphony 1 C Major","Movement 2"),
  (042,03,"Beethoven, Ludwig van","Symphony 1 C Major","Movement 3"),
  (042,04,"Beethoven, Ludwig van","Symphony 1 C Major","Movement 4"),
  (042,05,"Beethoven, Ludwig van","Symphony 3 E Flat Major","Movement 1"),
  (042,06,"Beethoven, Ludwig van","Symphony 3 E Flat Major","Movement 2"),
  (042,07,"Beethoven, Ludwig van","Symphony 3 E Flat Major","Movement 3"),
  (042,08,"Beethoven, Ludwig van","Symphony 3 E Flat Major","Movement 4"),
  (042,09,"Beethoven, Ludwig van","Symphony 8 F Major","Movement 1"),
  (043,01,"Beethoven, Ludwig van","Symphony 8 F Major","Movement 2"),
  (043,02,"Beethoven, Ludwig van","Symphony 8 F Major","Movement 3"),
  (043,03,"Beethoven, Ludwig van","Symphony 8 F Major","Movement 4"),
  (043,04,"Beethoven, Ludwig van","Symphony 9 D Minor","Movement 1"),
  (043,05,"Beethoven, Ludwig van","Symphony 9 D Minor","Movement 2"),
  (043,06,"Beethoven, Ludwig van","Symphony 9 D Minor","Movement 3"),
  (044,01,"Beethoven, Ludwig van","Symphony 9 D Minor","Movement 4"),
  (044,02,"Beethoven, Ludwig van","Piano Concerto 5 E Flat Major","Movement 1"),
  (044,03,"Beethoven, Ludwig van","Piano Concerto 5 E Flat Major","Movement 2"),
  (044,04,"Beethoven, Ludwig van","Piano Concerto 5 E Flat Major","Movement 3"),
  (044,05,"Beethoven, Ludwig van","Creatures of Prometheus","Prometheus Overture"),
  (044,06,"Beethoven, Ludwig van","Creatures of Prometheus","Act 1 Movement 1"),
  (044,07,"Beethoven, Ludwig van","Creatures of Prometheus","Act 1 Movement 2"),
  (045,01,"Beethoven, Ludwig van","Creatures of Prometheus","Act 1 Movement 3"),
  (045,02,"Beethoven, Ludwig van","Creatures of Prometheus","Act 2 Movement 4"),
  (045,03,"Beethoven, Ludwig van","Creatures of Prometheus","Act 2 Movement 5"),
  (045,04,"Beethoven, Ludwig van","Creatures of Prometheus","Act 2 Movement 8"),
  (045,05,"Beethoven, Ludwig van","Creatures of Prometheus","Act 2 Movement 9"),
  (045,06,"Beethoven, Ludwig van","Creatures of Prometheus","Act 2 Movement 10"),
  (045,07,"Beethoven, Ludwig van","Creatures of Prometheus","Act 2 Movement 15"),
  (045,08,"Beethoven, Ludwig van","Creatures of Prometheus","Act 2 Movement 16"),
  (045,09,"Chopin, Frederic F.","Chopin Preludes","Prelude C Major"),
  (045,10,"Chopin, Frederic F.","Chopin Preludes","Prelude A Minor"),
  (045,11,"Chopin, Frederic F.","Chopin Preludes","Prelude G Major"),
  (045,12,"Chopin, Frederic F.","Chopin Preludes","Prelude E Minor"),
  (045,13,"Chopin, Frederic F.","Chopin Preludes","Prelude D Major"),
  (045,14,"Chopin, Frederic F.","Chopin Preludes","Prelude B Minor"),
  (045,15,"Chopin, Frederic F.","Chopin Preludes","Prelude A Major"),
  (045,16,"Chopin, Frederic F.","Chopin Preludes","Prelude F Sharp Minor"),
  (045,17,"Chopin, Frederic F.","Chopin Preludes","Prelude E Major"),
  (045,18,"Chopin, Frederic F.","Chopin Preludes","Prelude C Sharp Minor"),
  (045,19,"Chopin, Frederic F.","Chopin Preludes","Prelude B Major"),
  (045,20,"Chopin, Frederic F.","Chopin Preludes","Prelude G Sharp Minor"),
  (045,21,"Chopin, Frederic F.","Chopin Preludes","Prelude F Sharp Major"),
  (045,22,"Chopin, Frederic F.","Chopin Preludes","Prelude E Flat Minor"),
  (045,23,"Chopin, Frederic F.","Chopin Preludes","Prelude D Flat Major"),
  (045,24,"Chopin, Frederic F.","Chopin Preludes","Prelude B Flat Minor"),
  (045,25,"Chopin, Frederic F.","Chopin Preludes","Prelude A Flat Major"),
  (045,26,"Chopin, Frederic F.","Chopin Preludes","Prelude F Minor"),
  (045,27,"Chopin, Frederic F.","Chopin Preludes","Prelude E Flat Major"),
  (045,28,"Chopin, Frederic F.","Chopin Preludes","Prelude C Minor"),
  (045,29,"Chopin, Frederic F.","Chopin Preludes","Prelude B Flat Major"),
  (045,30,"Chopin, Frederic F.","Chopin Preludes","Prelude G Minor"),
  (045,31,"Chopin, Frederic F.","Chopin Preludes","Prelude F Major"),
  (045,32,"Chopin, Frederic F.","Chopin Preludes","Prelude D Minor"),
  (046,01,"Dvorak, Antonin","Dvorak Symphony 5","Movement 1"),
  (046,02,"Dvorak, Antonin","Dvorak Symphony 5","Movement 2"),
  (046,03,"Dvorak, Antonin","Dvorak Symphony 5","Movement 3"),
  (046,04,"Dvorak, Antonin","Dvorak Symphony 5","Movement 4"),
  (046,05,"Dvorak, Antonin","Dvorak Symphony 7","Movement 1"),
  (046,06,"Dvorak, Antonin","Dvorak Symphony 7","Movement 2"),
  (046,07,"Dvorak, Antonin","Dvorak Symphony 7","Movement 3"),
  (047,01,"Dvorak, Antonin","Dvorak Symphony 7","Movement 4"),
  (047,02,"Grieg, Edvard H.","Peer Gynt","Prelude"),
  (047,03,"Grieg, Edvard H.","Peer Gynt","Morning Mood"),
  (047,04,"Grieg, Edvard H.","Peer Gynt","The Death of  †se"),
  (047,05,"Grieg, Edvard H.","Peer Gynt","Anitra's Dance"),
  (047,06,"Grieg, Edvard H.","Peer Gynt","In the Hall of the Mountain King"),
  (047,07,"Grieg, Edvard H.","Peer Gynt","Ingrid's Abduction and Lament"),
  (047,08,"Grieg, Edvard H.","Peer Gynt","Arab Dance"),
  (047,09,"Grieg, Edvard H.","Peer Gynt","Peer Gynt's Home-Coming"),
  (047,10,"Grieg, Edvard H.","Peer Gynt","Solvejg's Song"),
  (047,11,"Grieg, Edvard H.","Peer Gynt","Dance of the Mountain King's Daughter"),
  (047,12,"Handel, George F.","Royal Fireworks Music","Overture"),
  (047,13,"Handel, George F.","Royal Fireworks Music","Bouree"),
  (047,14,"Handel, George F.","Royal Fireworks Music","La Paix"),
  (047,15,"Handel, George F.","Royal Fireworks Music","La Rejouissance"),
  (047,16,"Handel, George F.","Royal Fireworks Music","Minuets 1/2"),
  (048,01,"Handel, George F.","Concerto 2","Concerto Grosso 2"),
  (048,02,"Handel, George F.","Concerto 5","Concerto Grosso 5"),
  (048,03,"Haydn, Franz J.","Symphony 92","Movement 1"),
  (048,04,"Haydn, Franz J.","Symphony 92","Movement 2"),
  (048,05,"Haydn, Franz J.","Symphony 92","Movement 3"),
  (048,06,"Haydn, Franz J.","Symphony 92","Movement 4"),
  (048,07,"Haydn, Franz J.","Symphony 104","Movement 1"),
  (048,08,"Haydn, Franz J.","Symphony 104","Movement 2"),
  (048,09,"Haydn, Franz J.","Symphony 104","Movement 3"),
  (048,10,"Haydn, Franz J.","Symphony 104","Movement 4"),
  (049,01,"Holst, Gustav T.","Holst Planets","Mars"),
  (049,02,"Holst, Gustav T.","Holst Planets","Venus"),
  (049,03,"Holst, Gustav T.","Holst Planets","Mercury"),
  (049,04,"Holst, Gustav T.","Holst Planets","Jupiter"),
  (049,05,"Holst, Gustav T.","Holst Planets","Saturn"),
  (049,06,"Holst, Gustav T.","Holst Planets","Uranus"),
  (049,07,"Holst, Gustav T.","Holst Planets","Neptune"),
  (049,08,"Ligeti, Gyoergy","Ligeti Lontano","Lontano"),
  (049,09,"Ligeti, Gyoergy","Ligeti Continuum","Continuum"),
  (049,10,"Carlos, Walter","Variations for Flute/Electronic Sound","Variations for Flute and Electronic Sound"),
  (049,11,"Carlos, Walter","Dialogues for Piano/Two Loudspeakers","Dialogues for Piano and Two Loudspeakers"),
  (050,01,"Ligeti, Gyoergy","Ligeti Requiem","Requiem"),
  (050,02,"Massenet, Jules E. F.","Le Cid","Castillane"),
  (050,03,"Massenet, Jules E. F.","Le Cid","Andalouse"),
  (050,04,"Massenet, Jules E. F.","Le Cid","Aragonaire"),
  (050,05,"Massenet, Jules E. F.","Le Cid","Aubade"),
  (050,06,"Massenet, Jules E. F.","Le Cid","Catalane"),
  (050,07,"Massenet, Jules E. F.","Le Cid","Madrilene"),
  (050,08,"Massenet, Jules E. F.","Le Cid","Navarraise"),
  (050,09,"Massenet, Jules E. F.","Scenes Pittoresques","Marche"),
  (050,10,"Massenet, Jules E. F.","Scenes Pittoresques","Air de Ballet"),
  (050,11,"Massenet, Jules E. F.","Scenes Pittoresques","Angelus"),
  (050,12,"Massenet, Jules E. F.","Scenes Pittoresques","Fete Boheme"),
  (050,13,"Massenet, Jules E. F.","Scenes Pittoresques","The Last Sleep of the Virgin"),
  (051,01,"Mahler, Gustav","Symphony 1","Movement 1"),
  (051,02,"Mahler, Gustav","Symphony 1","Movement 2"),
  (051,03,"Mahler, Gustav","Symphony 1","Movement 3"),
  (051,04,"Mahler, Gustav","Symphony 1","Movement 4"),
  (051,05,"Mahler, Gustav","Symphony 4","Movement 1"),
  (052,01,"Mahler, Gustav","Symphony 4","Movement 2"),
  (052,02,"Mahler, Gustav","Symphony 4","Movement 3"),
  (052,03,"Mahler, Gustav","Symphony 4","Movement 4"),
  (052,04,"Mussorgsky, Modest P.","Pictures at an Exhibition","Promenade"),
  (052,05,"Mussorgsky, Modest P.","Pictures at an Exhibition","Gnome"),
  (052,06,"Mussorgsky, Modest P.","Pictures at an Exhibition","Promenade"),
  (052,07,"Mussorgsky, Modest P.","Pictures at an Exhibition","The Old Castle"),
  (052,08,"Mussorgsky, Modest P.","Pictures at an Exhibition","Promenade"),
  (052,09,"Mussorgsky, Modest P.","Pictures at an Exhibition","Tuileries"),
  (052,10,"Mussorgsky, Modest P.","Pictures at an Exhibition","Bydlo"),
  (052,11,"Mussorgsky, Modest P.","Pictures at an Exhibition","Promenade"),
  (052,12,"Mussorgsky, Modest P.","Pictures at an Exhibition","Ballet of the Unhatched Chicks"),
  (052,13,"Mussorgsky, Modest P.","Pictures at an Exhibition","Two Polish Jews"),
  (052,14,"Mussorgsky, Modest P.","Pictures at an Exhibition","Limoges"),
  (052,15,"Mussorgsky, Modest P.","Pictures at an Exhibition","Catacombs"),
  (052,16,"Mussorgsky, Modest P.","Pictures at an Exhibition","The Hut on Fowl's Legs"),
  (052,17,"Mussorgsky, Modest P.","Pictures at an Exhibition","The Great Gate at Kiev"),
  (053,01,"Respighi, Ottorino","Fountains of Rome","Fountains of Rome"),
  (053,02,"Respighi, Ottorino","Pines of Rome","Pines of Rome"),
  (053,03,"Mendelssohn, Felix","Symphony 3","Movement 1"),
  (053,04,"Mendelssohn, Felix","Symphony 3","Movement 2"),
  (053,05,"Mendelssohn, Felix","Symphony 3","Movement 3"),
  (053,06,"Mendelssohn, Felix","Symphony 3","Movement 4"),
  (054,01,"Mendelssohn, Felix","Hebrides Overture","Hebrides Overture"),
  (054,02,"Mozart, Wolfgang A.","Symphony 35","Movement 1"),
  (054,03,"Mozart, Wolfgang A.","Symphony 35","Movement 2"),
  (054,04,"Mozart, Wolfgang A.","Symphony 35","Movement 3"),
  (054,05,"Mozart, Wolfgang A.","Symphony 35","Movement 4"),
  (054,06,"Mozart, Wolfgang A.","Symphony 35","Movement 1"),
  (054,07,"Mozart, Wolfgang A.","Symphony 35","Movement 2"),
  (054,08,"Mozart, Wolfgang A.","Symphony 35","Movement 3"),
  (054,09,"Mozart, Wolfgang A.","Symphony 35","Movement 4"),
  (054,10,"Mozart, Wolfgang A.","Capriccio Espagnol","Capriccio Espagnol"),
  (055,01,"Rimsky-Korsakov, Nikolay A.","Scheherezade","The Sea and Sinbad's Ship"),
  (055,02,"Rimsky-Korsakov, Nikolay A.","Scheherezade","The Story of the Kelender Prince"),
  (055,03,"Rimsky-Korsakov, Nikolay A.","Scheherezade","The Young Prince and The Young Princess"),
  (055,04,"Rimsky-Korsakov, Nikolay A.","Scheherezade","Festival in Bagdad"),
  (055,05,"Rimsky-Korsakov, Nikolay A.","Night on Bare Mountain","Night on Bare Mountain"),
  (055,06,"Prokofiev, Sergey S.","Classical Symphony","Movement 1"),
  (055,07,"Prokofiev, Sergey S.","Classical Symphony","Movement 2"),
  (055,08,"Prokofiev, Sergey S.","Classical Symphony","Movement 3"),
  (055,09,"Prokofiev, Sergey S.","Classical Symphony","Movement 4"),
  (056,01,"Shostakovich, Dmitri ","Symphony 1","Movement 1"),
  (056,02,"Shostakovich, Dmitri ","Symphony 1","Movement 2"),
  (056,03,"Shostakovich, Dmitri ","Symphony 1","Movement 3"),
  (056,04,"Shostakovich, Dmitri ","Symphony 1","Movement 4"),
  (056,05,"Shostakovich, Dmitri ","Symphony 10","Movement 1"),
  (056,06,"Shostakovich, Dmitri ","Symphony 10","Movement 2"),
  (056,07,"Shostakovich, Dmitri ","Symphony 10","Movement 3"),
  (057,01,"Shostakovich, Dmitri ","Symphony 10","Movement 4"),
  (057,02,"Sibelius, Jean","Sibelius Symphony 2","Movement 1"),
  (057,03,"Sibelius, Jean","Sibelius Symphony 2","Movement 2"),
  (057,04,"Sibelius, Jean","Sibelius Symphony 2","Movement 3"),
  (057,05,"Sibelius, Jean","Sibelius Symphony 2","Movement 4"),
  (057,06,"Sibelius, Jean","En Saga","En Saga"),
  (058,01,"Sibelius, Jean","Swan of Tuonela","Swan of Tuonela"),
  (058,02,"Sibelius, Jean","Finlandia","Finlandia"),
  (058,03,"Sibelius, Jean","Karelia Suite","Karelia Suite"),
  (058,04,"Britten, Benjamin","Young Person's Guide","Young Person's Guide to The Orchestra"),
  (058,05,"Strauss, Johann","Strauss Waltzes","Blue Danbube Waltz"),
  (058,06,"Strauss, Johann","Strauss Waltzes","Pizzicato Polka"),
  (058,07,"Strauss, Johann","Strauss Waltzes","Roses from The South Waltz"),
  (058,08,"Strauss, Johann","Strauss Waltzes","The Hunt Polka"),
  (059,01,"Strauss, Johann","Strauss Waltzes","1001 Nights Waltz"),
  (059,02,"Strauss, Johann","Strauss Waltzes","Tales from the Vienna Woods Waltz"),
  (059,03,"Strauss, Johann","Strauss Waltzes","Egyptian March"),
  (059,04,"Strauss, Johann","Strauss Waltzes","Vienna Blood Waltz"),
  (059,05,"Strauss, Johann","Strauss Waltzes","Perpetuum Mobile"),
  (059,06,"Strauss, Johann","Strauss Waltzes","Voices of Spring Waltz"),
  (059,07,"Strauss, Johann","Strauss Waltzes","Gipsy Baron Overture"),
  (059,08,"Strauss, Johann","Strauss Waltzes","Artist's Life Waltz"),
  (059,09,"Strauss, Johann","Strauss Waltzes","Neue Pizzacato Waltz"),
  (059,10,"Strauss, Johann","Strauss Waltzes","Emperor Waltz"),
  (059,11,"Strauss, Johann","Strauss Waltzes","Thunder and Lightning Polka"),
  (059,12,"Strauss, Johann","Strauss Waltzes","Explosions Polka"),
  (060,01,"Strauss, Johann","Strauss Waltzes","Die Fledermaus Overture"),
  (060,02,"Strauss, Johann","Strauss Waltzes","Wine, Women and Song Waltz"),
  (060,03,"Strauss, Johann","Strauss Waltzes","Du und Du Waltz"),
  (060,04,"Strauss, Johann","Also Sprach Zarathustra","Also Sprach Zarathustra"),
  (060,05,"Stravinsky, Igor F.","Rite of Spring","Adolescent Dance"),
  (060,06,"Stravinsky, Igor F.","Rite of Spring","Spring Rounds"),
  (060,07,"Stravinsky, Igor F.","Rite of Spring","Rival City Games"),
  (060,08,"Stravinsky, Igor F.","Rite of Spring","Funeral of The Sage"),
  (060,09,"Stravinsky, Igor F.","Rite of Spring","Adoration of The Earth"),
  (061,01,"Stravinsky, Igor F.","Rite of Spring","Introduction"),
  (061,02,"Stravinsky, Igor F.","Rite of Spring","Mysterious Adolescent Circles"),
  (061,03,"Stravinsky, Igor F.","Rite of Spring","Call The Ancestors"),
  (061,04,"Stravinsky, Igor F.","Rite of Spring","Ritual Dance"),
  (061,05,"Stravinsky, Igor F.","Firebird","Firebird Ballet Suite"),
  (061,06,"Stravinsky, Igor F.","Petrushka","Petrushka Ballet"),
  (062,01,"Sullivan, Arthur S.","The Mikado","The Mikado"),
  (062,02,"Sullivan, Arthur S.","The Gondoliers","The Gondoliers"),
  (062,03,"Sullivan, Arthur S.","The Yeomen of The Guard","The Yeomen of The Guard"),
  (062,04,"Sullivan, Arthur S.","The Pirates of Penzance","The Pirates of Penzance"),
  (062,05,"Sullivan, Arthur S.","HMS Pinafore","HMS Pinafore"),
  (062,06,"Sullivan, Arthur S.","Iolanthe","Iolanthe"),
  (062,07,"Sullivan, Arthur S.","The Mikado","For He's gone and married Yum-Yum"),
  (062,08,"Sullivan, Arthur S.","Pineapple Poll","Opening Dance"),
  (062,09,"Sullivan, Arthur S.","Pineapple Poll","Poll's Solo"),
  (062,10,"Sullivan, Arthur S.","Pineapple Poll","Belaye's Solo"),
  (062,11,"Sullivan, Arthur S.","Pineapple Poll","Pas de Trois"),
  (062,12,"Sullivan, Arthur S.","Pineapple Poll","Finale"),
  (062,13,"Sullivan, Arthur S.","Pineapple Poll","Poll's Solo"),
  (062,14,"Sullivan, Arthur S.","Pineapple Poll","Jasper's Solo"),
  (062,15,"Sullivan, Arthur S.","Pineapple Poll","Belaye's Solo"),
  (062,16,"Sullivan, Arthur S.","Pineapple Poll","Poll's Solo"),
  (063,01,"Sullivan, Arthur S.","Pineapple Poll","Entry of Belaye"),
  (063,02,"Sullivan, Arthur S.","Pineapple Poll","Reconciliation"),
  (063,03,"Sullivan, Arthur S.","Pineapple Poll","Grand Finale"),
  (063,04,"Tchaikovsky, Piotr I.","Russian Selection","'Eugene Onegin' Polonaise"),
  (063,05,"Tchaikovsky, Piotr I.","Russian Selection","'Mazeppa' Maria's Lullaby"),
  (063,06,"Tchaikovsky, Piotr I.","Russian Selection","'Swan Lake' Scene"),
  (063,07,"Tchaikovsky, Piotr I.","Russian Selection","'Swan Lake' Danse Espagnole"),
  (063,08,"Schumann, Robert","Russian Selection","Nacthstueck"),
  (063,09,"Liadov, Anatol K.","Russian Selection","A Musical Snuff-Box"),
  (063,10,"Rachmaninov, Sergey V.","Russian Selection","'Three Russian Songs' Across The River"),
  (063,11,"Sibelius, Jean","Russian Selection","Humoresque"),
  (063,12,"Prokofiev, Sergey S.","Russian Selection","'Love of Three Oranges' March"),
  (063,13,"Prokofiev, Sergey S.","Russian Selection","'Love of Three Oranges' Scherzo"),
  (063,14,"Bizet, Georges","Russian Selection","'Carmen' Habanera"),
  (063,15,"Shaporin, Yuri A.","Russian Selection","'Battle for The Russian Land' The Dawn"),
  (063,16,"Shostakovich, Dmitri ","Russian Selection","Symphony 14 On Watch"),
  (063,17,"Vainberg","Russian Selection","Violin Concerto Allegretto"),
  (063,18,"Prokofiev, Sergey S.","Russian Selection","'Alexander Nevsky' Entry into Pskov"),
  (063,19,"Dvorak, Antonin","Dvorak Serenade for Strings","Moderato"),
  (063,20,"Dvorak, Antonin","Dvorak Serenade for Strings","Tempo di Valse"),
  (064,01,"Dvorak, Antonin","Dvorak Serenade for Strings","Scherzo"),
  (064,02,"Dvorak, Antonin","Dvorak Serenade for Strings","Largetto"),
  (064,03,"Dvorak, Antonin","Dvorak Serenade for Strings","Allegro Vivace"),
  (064,04,"Tchaikovsky, Piotr I.","Tchaikovsky Serenade for Strings","Andante non Troppo"),
  (064,05,"Tchaikovsky, Piotr I.","Tchaikovsky Serenade for Strings","Waltz"),
  (064,06,"Tchaikovsky, Piotr I.","Tchaikovsky Serenade for Strings","Elegy"),
  (064,07,"Tchaikovsky, Piotr I.","Tchaikovsky Serenade for Strings","Andante"),
  (064,08,"Tchaikovsky, Piotr I.","Nutcracker Suite","Overture"),
  (064,09,"Tchaikovsky, Piotr I.","Nutcracker Suite","Marche"),
  (064,10,"Tchaikovsky, Piotr I.","Nutcracker Suite","Petit Galop des Enfants"),
  (064,11,"Tchaikovsky, Piotr I.","Nutcracker Suite","Scene"),
  (064,12,"Tchaikovsky, Piotr I.","Nutcracker Suite","Valse de Flocons de Neige"),
  (064,13,"Tchaikovsky, Piotr I.","Nutcracker Suite","Le Chocolat"),
  (064,14,"Tchaikovsky, Piotr I.","Nutcracker Suite","Le Cafe"),
  (064,15,"Tchaikovsky, Piotr I.","Nutcracker Suite","Le The"),
  (064,16,"Tchaikovsky, Piotr I.","Nutcracker Suite","Trepak"),
  (064,17,"Tchaikovsky, Piotr I.","Nutcracker Suite","Danse des Mirlitons"),
  (065,01,"Tchaikovsky, Piotr I.","Nutcracker Suite","Valse des Fleurs"),
  (065,02,"Tchaikovsky, Piotr I.","Nutcracker Suite","Pas de Deux"),
  (065,03,"Tchaikovsky, Piotr I.","Nutcracker Suite","Pour Le Danseur"),
  (065,04,"Tchaikovsky, Piotr I.","Nutcracker Suite","Pour La Danseuse"),
  (065,05,"Tchaikovsky, Piotr I.","Nutcracker Suite","Coda"),
  (065,06,"Tchaikovsky, Piotr I.","Nutcracker Suite","Valse Finale"),
  (065,07,"Tchaikovsky, Piotr I.","Symphony 1","Movement 1"),
  (065,08,"Tchaikovsky, Piotr I.","Symphony 1","Movement 2"),
  (065,09,"Tchaikovsky, Piotr I.","Symphony 1","Movement 3"),
  (065,10,"Tchaikovsky, Piotr I.","Symphony 1","Movement 4"),
  (065,11,"Tchaikovsky, Piotr I.","Symphony 2","Movement 1"),
  (066,01,"Tchaikovsky, Piotr I.","Symphony 2","Movement 2"),
  (066,02,"Tchaikovsky, Piotr I.","Symphony 2","Movement 3"),
  (066,03,"Tchaikovsky, Piotr I.","Symphony 2","Movement 4"),
  (066,04,"Tchaikovsky, Piotr I.","Symphony 6","Movement 1"),
  (066,05,"Tchaikovsky, Piotr I.","Symphony 6","Movement 2"),
  (066,06,"Tchaikovsky, Piotr I.","Symphony 6","Movement 3"),
  (066,07,"Tchaikovsky, Piotr I.","Symphony 6","Movement 4"),
  (067,01,"Tchaikovsky, Piotr I.","Piano Concerto 1","Movement 1"),
  (067,02,"Tchaikovsky, Piotr I.","Piano Concerto 1","Movement 2"),
  (067,03,"Tchaikovsky, Piotr I.","Piano Concerto 1","Movement 3"),
  (067,04,"Litolff, Henry C.","Litolff Scherzo","Scherzo"),
  (067,05,"Tchaikovsky, Piotr I.","1812 Overture","1812 Overture"),
  (067,06,"Berlioz, Hector","Hungarian March","'Damnation of Faust' Hungarian March"),
  (067,07,"Sibelius, Jean","Valse Triste","Valse Triste"),
  (068,01,"Liszt, Franz","Hungarian Rhapsody 2","Hungarian Rhapsody 2"),
  (068,02,"Weber, Carl M. E. von","Invitation to The Dance","Invitation to The Dance"),
  (068,03,"Vivaldi, Antonio","Four Seasons","Spring"),
  (068,04,"Vivaldi, Antonio","Four Seasons","Summer"),
  (068,05,"Vivaldi, Antonio","Four Seasons","Autumn"),
  (068,06,"Vivaldi, Antonio","Four Seasons","Winter"),
  (068,07,"Zamfir, Gheorghi","The Light of Experience","The Light of Experience"),
  (069,01,"Bach, Johann S.","Bach Mass B Minor","Kyrie Eleison"),
  (069,02,"Bach, Johann S.","Bach Mass B Minor","Christe Eleison"),
  (069,03,"Bach, Johann S.","Bach Mass B Minor","Kyrie Eleison"),
  (069,04,"Bach, Johann S.","Bach Mass B Minor","Gloria in Excelsis Deo"),
  (069,05,"Bach, Johann S.","Bach Mass B Minor","Laudamus Te"),
  (069,06,"Bach, Johann S.","Bach Mass B Minor","Gratias agimus Tibi"),
  (069,07,"Bach, Johann S.","Bach Mass B Minor","Domini Deus"),
  (069,08,"Bach, Johann S.","Bach Mass B Minor","Qui tollis"),
  (069,09,"Bach, Johann S.","Bach Mass B Minor","Qui sedes"),
  (069,10,"Bach, Johann S.","Bach Mass B Minor","Quoniam Tu Solus Sanctus"),
  (069,11,"Bach, Johann S.","Bach Mass B Minor","Cum Sancto Spiritu"),
  (069,12,"Bach, Johann S.","Bach Mass B Minor","Credo in Unum Deum"),
  (069,13,"Bach, Johann S.","Bach Mass B Minor","Patrem Omnipotentem"),
  (069,14,"Bach, Johann S.","Bach Mass B Minor","Et in Unum Dominum"),
  (070,01,"Bach, Johann S.","Bach Mass B Minor","Et Incarnatus est"),
  (070,02,"Bach, Johann S.","Bach Mass B Minor","Crucifixus"),
  (070,03,"Bach, Johann S.","Bach Mass B Minor","Et resurrexit"),
  (070,04,"Bach, Johann S.","Bach Mass B Minor","Et in Spiritum Sanctum"),
  (070,05,"Bach, Johann S.","Bach Mass B Minor","Confiteor"),
  (070,06,"Bach, Johann S.","Bach Mass B Minor","Sanctus, Sanctus, Sanctus"),
  (070,07,"Bach, Johann S.","Bach Mass B Minor","Osanna"),
  (070,08,"Bach, Johann S.","Bach Mass B Minor","Benedictus"),
  (070,09,"Bach, Johann S.","Bach Mass B Minor","Osanna"),
  (070,10,"Bach, Johann S.","Bach Mass B Minor","Agnus Dei"),
  (070,11,"Bach, Johann S.","Bach Mass B Minor","Dona Nobis Pacem"),
  (070,12,"Bach, Johann S.","Bach Cantata 129","Gelobet sei de Herr"),
  (070,13,"Bach, Johann S.","Bach Cantata 129","Gelobet sei de Herr"),
  (070,14,"Bach, Johann S.","Bach Cantata 129","Gelobet sei de Herr"),
  (070,15,"Bach, Johann S.","Bach Cantata 129","Gelobet sei de Herr"),
  (070,16,"Bach, Johann S.","Bach Cantata 129","Dem wir Heilig"),
  (071,01,"Bach, Johann S.","Bach Cantata 119","Preise, Jerusalem"),
  (071,02,"Bach, Johann S.","Bach Cantata 119","Erwuenschter Tag"),
  (071,03,"Bach, Johann S.","Bach Cantata 119","Wohl dem"),
  (071,04,"Bach, Johann S.","Bach Cantata 119","Es ist der Herr"),
  (071,05,"Bach, Johann S.","Bach Cantata 119","Des Griedens"),
  (071,06,"Bach, Johann S.","Bach Cantata 119","Nun, nun"),
  (071,07,"Bach, Johann S.","Bach Cantata 119","Wohlan!"),
  (071,08,"Bach, Johann S.","Bach Cantata 119","Hilf deinem Volk"),
  (071,09,"Bach, Johann S.","Bach Magnificat","Magnificat"),
  (071,10,"Bach, Johann S.","Bach Magnificat","Et exsultavit"),
  (071,11,"Bach, Johann S.","Bach Magnificat","Quia respexit"),
  (071,12,"Bach, Johann S.","Bach Magnificat","Omnes Generationes"),
  (071,13,"Bach, Johann S.","Bach Magnificat","Quia fecit Mihi Magna"),
  (071,14,"Bach, Johann S.","Bach Magnificat","Et Misericordia"),
  (071,15,"Bach, Johann S.","Bach Magnificat","Fecit Potentiam"),
  (071,16,"Bach, Johann S.","Bach Magnificat","Deposuit Potentes"),
  (071,17,"Bach, Johann S.","Bach Magnificat","Esurientes implevit Bonis"),
  (071,18,"Bach, Johann S.","Bach Magnificat","Suscepit Israel"),
  (071,19,"Bach, Johann S.","Bach Magnificat","Sicut Locutus est"),
  (071,20,"Bach, Johann S.","Bach Magnificat","Gloria Patri"),
  (071,21,"Beethoven, Ludwig van","The Ruins of Athens","Overture"),
  (071,22,"Beethoven, Ludwig van","The Ruins of Athens","Daughter of Mighty Zeus"),
  (071,23,"Beethoven, Ludwig van","The Ruins of Athens","Without Guilt"),
  (071,24,"Beethoven, Ludwig van","The Ruins of Athens","Chorus of Dervishes"),
  (071,25,"Beethoven, Ludwig van","The Ruins of Athens","Turkish March"),
  (072,01,"Beethoven, Ludwig van","The Ruins of Athens","Decorate The Altars"),
  (072,02,"Beethoven, Ludwig van","The Ruins of Athens","We have Receptive Hearts"),
  (072,03,"Beethoven, Ludwig van","The Ruins of Athens","Hail to The King"),
  (072,04,"Beethoven, Ludwig van","King Stephan ","Overture"),
  (072,05,"Beethoven, Ludwig van","King Stephan ","Resting from His Deeds"),
  (072,06,"Beethoven, Ludwig van","King Stephan ","On A Dark Misleading path"),
  (072,07,"Beethoven, Ludwig van","King Stephan ","Victory March"),
  (072,08,"Beethoven, Ludwig van","King Stephan ","Where Innocence"),
  (072,09,"Beethoven, Ludwig van","King Stephan ","A Radiant New Sun"),
  (072,10,"Beethoven, Ludwig van","King Stephan ","Hail! Hail!"),
  (072,11,"Beethoven, Ludwig van","Missa Solemnis","Kyrie"),
  (072,12,"Beethoven, Ludwig van","Missa Solemnis","Gloria"),
  (073,01,"Beethoven, Ludwig van","Missa Solemnis","Credo"),
  (073,02,"Beethoven, Ludwig van","Missa Solemnis","Sanctus"),
  (073,03,"Beethoven, Ludwig van","Missa Solemnis","Agnus Dei"),
  (073,04,"Bizet, Georges","Carmen","Prelude"),
  (073,05,"Bizet, Georges","Carmen","With the Mounted Guard"),
  (073,06,"Bizet, Georges","Carmen","Entrance of Carmen"),
  (073,07,"Bizet, Georges","Carmen","Habanera"),
  (073,08,"Bizet, Georges","Carmen","Seguillada and Duet"),
  (073,09,"Bizet, Georges","Carmen","Gypsy Song"),
  (073,10,"Bizet, Georges","Carmen","Toreador's Song"),
  (074,01,"Bizet, Georges","Carmen","Flower Song"),
  (074,02,"Bizet, Georges","Carmen","Card Scene"),
  (074,03,"Bizet, Georges","Carmen","Micaela's Air"),
  (074,04,"Bizet, Georges","Carmen","Here they are!"),
  (074,05,"Bruckner, Anton","Bruckner Te Deum","Te Deum laudamus"),
  (074,06,"Bruckner, Anton","Bruckner Te Deum","Te ergo quaesumus"),
  (074,07,"Bruckner, Anton","Bruckner Te Deum","Aeterna fac cum Sanctis Tuis"),
  (074,08,"Bruckner, Anton","Bruckner Te Deum","Salvum fac Populum Tuum"),
  (074,09,"Bruckner, Anton","Bruckner Te Deum","In Te, Domine, speravi"),
  (074,10,"Attaingnant, Pierre","Le Jardin Musical","Pavane"),
  (074,11,"Attaingnant, Pierre","Le Jardin Musical","Galliarde"),
  (074,12,"Attaingnant, Pierre","Le Jardin Musical","Branle de Champaigne"),
  (074,13,"Attaingnant, Pierre","Le Jardin Musical","Branle d'Escosse"),
  (074,14,"Attaingnant, Pierre","Le Jardin Musical","Branle de Poictou"),
  (074,15,"Lasso, Orlando di","Le Jardin Musical","La Nuict Froide et Sombre"),
  (074,16,"Lasso, Orlando di","Le Jardin Musical","Fantaisie"),
  (074,17,"Lasso, Orlando di","Le Jardin Musical","La Belle Aronde"),
  (074,18,"Lasso, Orlando di","Le Jardin Musical","O Roze, Reyne Des Fleurs"),
  (074,19,"Janequin, Clement","Le Jardin Musical","Le Chant Des Oyseaux"),
  (074,20,"Praetorius, Michael","Le Jardin Musical","Pavane de Spaigne"),
  (074,21,"Praetorius, Michael","Le Jardin Musical","Volte"),
  (074,22,"Praetorius, Michael","Le Jardin Musical","La Rosette"),
  (074,23,"Praetorius, Michael","Le Jardin Musical","La Canarie"),
  (074,24,"Pres, Josquin des","Le Jardin Musical","Frottola 'El Grillo'"),
  (075,01,"Marenzio, Luca","Le Jardin Musical","Due Rose"),
  (075,02,"Gussago, C.","Le Jardin Musical","Sonata 'La Leona'"),
  (075,03,"Monteverdi, Claudio G. A.","Le Jardin Musical","Ecco mormorar L'Onde"),
  (075,04,"Susato, Tylmann","Le Jardin Musical","Basse Danse"),
  (075,05,"Susato, Tylmann","Le Jardin Musical","Ronde"),
  (075,06,"Susato, Tylmann","Le Jardin Musical","Salterelle"),
  (075,07,"Pres, Josquin des","Missa Pange Lingua","Kyrie"),
  (075,08,"Pres, Josquin des","Missa Pange Lingua","Gloria"),
  (075,09,"Pres, Josquin des","Missa Pange Lingua","Qui tollis"),
  (075,10,"Pres, Josquin des","Missa Pange Lingua","Credo"),
  (075,11,"Pres, Josquin des","Missa Pange Lingua","Et Incarnatus est"),
  (075,12,"Pres, Josquin des","Missa Pange Lingua","Crucifixus"),
  (075,13,"Pres, Josquin des","Missa Pange Lingua","Et in Spiritum Sanctum"),
  (075,14,"Pres, Josquin des","Missa Pange Lingua","Confiteor"),
  (075,15,"Pres, Josquin des","Missa Pange Lingua","Osanna"),
  (075,16,"Pres, Josquin des","Missa Pange Lingua","Benedictus"),
  (075,17,"Pres, Josquin des","Missa Pange Lingua","Osana"),
  (075,18,"Pres, Josquin des","Missa Pange Lingua","Agnus Dei"),
  (075,19,"Rue, Pierre de la","Missa pro Defunctis","Requiem Aeternam"),
  (075,20,"Rue, Pierre de la","Missa pro Defunctis","Te decet Hymnus"),
  (075,21,"Rue, Pierre de la","Missa pro Defunctis","Kyrie"),
  (075,22,"Rue, Pierre de la","Missa pro Defunctis","Sicut erat"),
  (075,23,"Rue, Pierre de la","Missa pro Defunctis","Domine Jesu Christe"),
  (075,24,"Rue, Pierre de la","Missa pro Defunctis","Hostias"),
  (075,25,"Rue, Pierre de la","Missa pro Defunctis","Sanctus"),
  (075,26,"Rue, Pierre de la","Missa pro Defunctis","Benedictus"),
  (075,27,"Rue, Pierre de la","Missa pro Defunctis","Agnus Dei"),
  (076,01,"Faure, Gabriel U.","Faure Requiem","Introit"),
  (076,02,"Faure, Gabriel U.","Faure Requiem","Kyrie"),
  (076,03,"Faure, Gabriel U.","Faure Requiem","Offertory"),
  (076,04,"Faure, Gabriel U.","Faure Requiem","Sanctus"),
  (076,05,"Faure, Gabriel U.","Faure Requiem","Pie Jesu"),
  (076,06,"Faure, Gabriel U.","Faure Requiem","Agnus Dei"),
  (076,07,"Faure, Gabriel U.","Faure Requiem","Libera Me"),
  (076,08,"Faure, Gabriel U.","Faure Requiem","In Paradisum"),
  (076,09,"Faure, Gabriel U.","Faure Pavane","Pavane"),
  (076,10,"Gounod, Charles F.","Faust","Vin ou Biere"),
  (076,11,"Gounod, Charles F.","Faust","O Sainte Medaille"),
  (076,12,"Gounod, Charles F.","Faust","Le Veau d'Or"),
  (076,13,"Gounod, Charles F.","Faust","Ainsi que La Brise Legere"),
  (076,14,"Gounod, Charles F.","Faust","Ne permettrez-vous pas?"),
  (076,15,"Gounod, Charles F.","Faust","Quel Trouble Inconnu me penetre?"),
  (076,16,"Gounod, Charles F.","Faust","Salut! Demeure Chaste et Pure"),
  (076,17,"Gounod, Charles F.","Faust","Jewel Song"),
  (077,01,"Gounod, Charles F.","Faust","Il se fait Tard"),
  (077,02,"Gounod, Charles F.","Faust","Soldier's Chorus"),
  (077,03,"Gounod, Charles F.","Faust","Mephistopheles' Serenade"),
  (077,04,"Gounod, Charles F.","Faust","Alert, Alerte"),
  (077,05,"Gounod, Charles F.","Faust","Christe est Ressuscite"),
  (077,06,"Mendelsson, Felix","Elijah","As God The Lord"),
  (077,07,"Mendelsson, Felix","Elijah","Help Lord!"),
  (077,08,"Mendelsson, Felix","Elijah","The Deeps afford No Water"),
  (077,09,"Mendelsson, Felix","Elijah","Lord! Bow Thine Ear"),
  (077,10,"Mendelsson, Felix","Elijah","Ye People"),
  (077,11,"Mendelsson, Felix","Elijah","Yet doth The Lord see It not"),
  (077,12,"Mendelsson, Felix","Elijah","Elijah! Get Thee Hence"),
  (077,13,"Mendelsson, Felix","Elijah","For He shall give His Angels"),
  (077,14,"Mendelsson, Felix","Elijah","Now Cherith's Brook"),
  (077,15,"Mendelsson, Felix","Elijah","What have I to do with Thee?"),
  (077,16,"Mendelsson, Felix","Elijah","Give Me Thy Son"),
  (077,17,"Mendelsson, Felix","Elijah","Blessed are The Men Who fear Him"),
  (077,18,"Mendelsson, Felix","Elijah","As God The Lord"),
  (077,19,"Mendelsson, Felix","Elijah","Baal We cry to Thee"),
  (077,20,"Mendelsson, Felix","Elijah","Draw Near"),
  (077,21,"Mendelsson, Felix","Elijah","Cast Thye Burden upon The Lord"),
  (077,22,"Mendelsson, Felix","Elijah","O Thou Who makest Thine Angels Spiritis"),
  (077,23,"Mendelsson, Felix","Elijah","Take All The Prophets of Baal"),
  (077,24,"Mendelsson, Felix","Elijah","Woe unto them"),
  (078,01,"Mendelsson, Felix","Elijah","O Man of God"),
  (078,02,"Mendelsson, Felix","Elijah","Thanks be to God"),
  (078,03,"Mendelsson, Felix","Elijah","Hear Ye Israel"),
  (078,04,"Mendelsson, Felix","Elijah","Be not afraid"),
  (078,05,"Mendelsson, Felix","Elijah","The Lord hath exalted Thee"),
  (078,06,"Mendelsson, Felix","Elijah","Woe to Him"),
  (078,07,"Mendelsson, Felix","Elijah","Man of God"),
  (078,08,"Mendelsson, Felix","Elijah","It is Enough"),
  (078,09,"Mendelsson, Felix","Elijah","Lift Thine Eyes to The Mountains"),
  (078,10,"Mendelsson, Felix","Elijah","He watching over Israel"),
  (078,11,"Mendelsson, Felix","Elijah","Arise Elijah"),
  (078,12,"Mendelsson, Felix","Elijah","O rest in The Lord"),
  (078,13,"Mendelsson, Felix","Elijah","He that shall endure to The End"),
  (078,14,"Mendelsson, Felix","Elijah","Night falleth round Me"),
  (078,15,"Mendelsson, Felix","Elijah","Behold! God the Lord passed by!"),
  (078,16,"Mendelsson, Felix","Elijah","Above Him stood the Seraphim"),
  (078,17,"Mendelsson, Felix","Elijah","I go on My Way"),
  (078,18,"Mendelsson, Felix","Elijah","Then did Elijah The Prophet"),
  (078,19,"Mendelsson, Felix","Elijah","Then shall The righteous"),
  (078,20,"Mendelsson, Felix","Elijah","Behold, God has sent Elijah"),
  (078,21,"Mendelsson, Felix","Elijah","But The Lord"),
  (078,22,"Mendelsson, Felix","Elijah","O come Everyone"),
  (078,23,"Mendelsson, Felix","Elijah","And then shall Your Light"),
  (079,01,"Mendelsson, Felix","The First Walpurgis Night","Overture"),
  (079,02,"Mendelsson, Felix","The First Walpurgis Night","May smiles again"),
  (079,03,"Mendelsson, Felix","The First Walpurgis Night","A Cleansing Snow"),
  (079,04,"Mendelsson, Felix","The First Walpurgis Night","Don't You know"),
  (079,05,"Mendelsson, Felix","The First Walpurgis Night","Yet He Who fears"),
  (079,06,"Mendelsson, Felix","The First Walpurgis Night","Spread out and search"),
  (079,07,"Mendelsson, Felix","The First Walpurgis Night","Let's outwit"),
  (079,08,"Mendelsson, Felix","The First Walpurgis Night","Come on!"),
  (079,09,"Mendelsson, Felix","The First Walpurgis Night","All Nature's Father"),
  (079,10,"Mendelsson, Felix","The First Walpurgis Night","Help!"),
  (079,11,"Mendelsson, Felix","The First Walpurgis Night","The Flame is purified"),
  (079,12,"Mendelsson, Felix","Infelice","Infelice"),
  (079,13,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Deus in Adjutorium"),
  (079,14,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Dixit Dominus"),
  (079,15,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Nigra sum"),
  (079,16,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Laudate Pueri"),
  (079,17,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Pulchra es"),
  (079,18,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Laetatus sum"),
  (079,19,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Duo Seraphim"),
  (080,01,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Nisi Dominus"),
  (080,02,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Audi Coelum"),
  (080,03,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Lauda Jerusalem"),
  (080,04,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Sancta Maria"),
  (080,05,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Ave Maris Stella"),
  (080,06,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Magnificat"),
  (080,07,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Et exultavit"),
  (080,08,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Quia respexit"),
  (080,09,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Quia fecit"),
  (080,10,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Et Misericordia"),
  (080,11,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Fecit Potentiam"),
  (080,12,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Deposuit"),
  (080,13,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Esurientes"),
  (080,14,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Suscepit Israel"),
  (080,15,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Sicut Locutus"),
  (080,16,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Gloria Patri"),
  (080,17,"Monteverdi, Claudio G. A.","Monteverdi Vespers","Sicut erat"),
  (080,18,"Mozart, Wolfgang A.","Magic Flute","Der Vogelfaenger bin ich ja"),
  (080,19,"Mozart, Wolfgang A.","Magic Flute","Dies Bildnis ist bezaubernd schoen"),
  (080,20,"Mozart, Wolfgang A.","Magic Flute","O zittre nicht, mein lieber Sohn!"),
  (080,21,"Mozart, Wolfgang A.","Magic Flute","Bei Maennern, welche Liebe fuehlen"),
  (080,22,"Mozart, Wolfgang A.","Magic Flute","Wie stark ist nicht dein Zauberton"),
  (081,01,"Mozart, Wolfgang A.","Magic Flute","Wenn Tugend"),
  (081,02,"Mozart, Wolfgang A.","Magic Flute","March of The Priests"),
  (081,03,"Mozart, Wolfgang A.","Magic Flute","Der Hoelle Rache kocht in meinem Herzen"),
  (081,04,"Mozart, Wolfgang A.","Magic Flute","In diesen heil'gen Hallen"),
  (081,05,"Mozart, Wolfgang A.","Magic Flute","Ach, ich fuehl's, es ist verschwunden!"),
  (081,06,"Mozart, Wolfgang A.","Magic Flute","Ein Maedchen oder Weibchen"),
  (081,07,"Mozart, Wolfgang A.","Magic Flute","Tamino mein! O welch ein Glueck!"),
  (081,08,"Mozart, Wolfgang A.","Magic Flute","Klinget, Gloeckchen, Klinget!"),
  (081,09,"Nicolai, Carl O. E.","Merry Wives of Windsor","Overture"),
  (081,10,"Nicolai, Carl O. E.","Merry Wives of Windsor","Why, did You ever hear The Like?"),
  (081,11,"Nicolai, Carl O. E.","Merry Wives of Windsor","Now come to Me, Wit, Gay Invention"),
  (081,12,"Nicolai, Carl O. E.","Merry Wives of Windsor","When that I was but A Little Tiny Boy"),
  (081,13,"Nicolai, Carl O. E.","Merry Wives of Windsor","My Greeting, Sir!"),
  (081,14,"Nicolai, Carl O. E.","Merry Wives of Windsor","Hark, The Lark sings in The Grove"),
  (081,15,"Nicolai, Carl O. E.","Merry Wives of Windsor","O Silver Moon"),
  (082,01,"Nicolai, Carl O. E.","Merry Wives of Windsor","My Maiden!"),
  (082,02,"Nicolai, Carl O. E.","Merry Wives of Windsor","So The Jest of This Night"),
  (082,03,"Offenbach, Jacques","Tales of Hoffmann","Glou, Glou, Glou"),
  (082,04,"Offenbach, Jacques","Tales of Hoffmann","Dans Les Roles Amoureux Langoureux"),
  (082,05,"Offenbach, Jacques","Tales of Hoffmann","Drig, Drig, Drig!"),
  (082,06,"Offenbach, Jacques","Tales of Hoffmann","Ile etait Une Fois"),
  (082,07,"Offenbach, Jacques","Tales of Hoffmann","Ma Maitresse?"),
  (082,08,"Offenbach, Jacques","Tales of Hoffmann","J'ai Des Yeux"),
  (082,09,"Offenbach, Jacques","Tales of Hoffmann","Ah! Vivre Deux n'avoir Qu'Une Meme Esperance"),
  (082,10,"Offenbach, Jacques","Tales of Hoffmann","Les Oiseaux dans La Charmille"),
  (082,11,"Offenbach, Jacques","Tales of Hoffmann","Voici Les Valseurs!"),
  (082,12,"Offenbach, Jacques","Tales of Hoffmann","Scintille Diamant"),
  (082,13,"Offenbach, Jacques","Tales of Hoffmann","Vous Me quittez?"),
  (082,14,"Offenbach, Jacques","Tales of Hoffmann","Belle Nuit"),
  (082,15,"Offenbach, Jacques","Tales of Hoffmann","Elle a fuit La Tourterelle"),
  (082,16,"Offenbach, Jacques","Tales of Hoffmann","J'ai Le Bonheur"),
  (082,17,"Offenbach, Jacques","Tales of Hoffmann","Tu ne chanteras plus?"),
  (082,18,"Offenbach, Jacques","Tales of Hoffmann","Voila Qu'Elle fut L'Histoire"),
  (082,19,"Offenbach, Jacques","Tales of Hoffmann","Allumons Le Punch"),
  (082,20,"Weber, Carl M. E. von","Opera Choruses","'Der Freischuetz' Huntsmen's Chorus"),
  (082,21,"Beethoven, Ludwig van","Opera Choruses","'Fidelio' Prisoners' Chorus"),
  (082,22,"Verdi, Giuseppe","Opera Choruses","'Il Trovatore' Gipsy Chorus"),
  (083,01,"Lortzing, Gustav Albert","Opera Choruses","'Zar und Zimmermann' Den hohen Herrrscher wuerdzig zu empfangen"),
  (083,02,"Wagner, Richard","Opera Choruses","'Tannhaeuser' Pilgrims' Chorus"),
  (083,03,"Verdi, Giuseppe","Opera Choruses","'Nabucco' Hebrew Captives' Chorus"),
  (083,04,"Verdi, Giuseppe","Opera Choruses","'Il Trovatore' Soldiers' Chorus"),
  (083,05,"Verdi, Giuseppe","Opera Choruses","'Aida' Triumph March"),
  (083,06,"Mascagni, Pietro","Opera Choruses","'Cavalleria Rusticana' Easter Hymn"),
  (083,07,"Orff, Carl","Carmina Burana","O Fortuna"),
  (083,08,"Orff, Carl","Carmina Burana","Fortune plango Vulnera"),
  (083,09,"Orff, Carl","Carmina Burana","Veris Leta facies"),
  (083,10,"Orff, Carl","Carmina Burana","Omnia Sol temperat"),
  (083,11,"Orff, Carl","Carmina Burana","Ecce Gratum"),
  (083,12,"Orff, Carl","Carmina Burana","Dance"),
  (083,13,"Orff, Carl","Carmina Burana","Floret Silva"),
  (083,14,"Orff, Carl","Carmina Burana","Chramer, gip die varwe mir"),
  (083,15,"Orff, Carl","Carmina Burana","Round Dance"),
  (083,16,"Orff, Carl","Carmina Burana","Were diu werlt alle min"),
  (083,17,"Orff, Carl","Carmina Burana","Estuans Interius"),
  (084,01,"Orff, Carl","Carmina Burana","Ego sum Abbas"),
  (084,02,"Orff, Carl","Carmina Burana","In Taberna quando sumus"),
  (084,03,"Orff, Carl","Carmina Burana","Amor volat undique"),
  (084,04,"Orff, Carl","Carmina Burana","Dies, Nox et Omnia"),
  (084,05,"Orff, Carl","Carmina Burana","Stetit Puella"),
  (084,06,"Orff, Carl","Carmina Burana","Circa Mea pectora"),
  (084,07,"Orff, Carl","Carmina Burana","Si Puer cum Puellula"),
  (084,08,"Orff, Carl","Carmina Burana","Veni, veni, venias"),
  (084,09,"Orff, Carl","Carmina Burana","In Trutina"),
  (084,10,"Orff, Carl","Carmina Burana","Tempus est Iocundum"),
  (084,11,"Orff, Carl","Carmina Burana","Dulcissime"),
  (084,12,"Orff, Carl","Carmina Burana","Ave Formosissima"),
  (084,13,"Orff, Carl","Carmina Burana","O Fortuna"),
  (084,14,"Orff, Carl","Catulli Carmina","Eis Aiona!"),
  (084,15,"Orff, Carl","Catulli Carmina","Odi et amo"),
  (084,16,"Orff, Carl","Catulli Carmina","Vivamus, Mea Lesbia"),
  (084,17,"Orff, Carl","Catulli Carmina","Ille Mi par esse Deo videtur"),
  (084,18,"Orff, Carl","Catulli Carmina","Caeli!"),
  (084,19,"Orff, Carl","Catulli Carmina","Nulli se dicit Mulier"),
  (084,20,"Orff, Carl","Catulli Carmina","Jucundum Mea Vita"),
  (084,21,"Orff, Carl","Catulli Carmina","Desine de Quoquam"),
  (084,22,"Orff, Carl","Catulli Carmina","Odi et amo"),
  (084,23,"Orff, Carl","Catulli Carmina","Amabo, Mea Dulcis Ipsilla"),
  (084,24,"Orff, Carl","Catulli Carmina","Ammiana Puella Defututa"),
  (084,25,"Orff, Carl","Catulli Carmina","Miser Catulle"),
  (084,26,"Orff, Carl","Catulli Carmina","Nulla potest Mulier"),
  (084,27,"Orff, Carl","Catulli Carmina","Eis Aiona!"),
  (084,28,"Rebroff, Ivan","Na Sdarowje","Na Sdarowje"),
  (084,29,"Nicolai, Carl O. E.","Na Sdarowje","Als Bueblein klein"),
  (084,30,"Kapitanoff, F.","Na Sdarowje","Der trunkene Pope"),
  (084,31,"Traditional","Na Sdarowje","Wuetend waelzt' sich einst im Bette"),
  (085,01,"Rebroff, Ivan","Na Sdarowje","Bessarabyanka"),
  (085,02,"Simon, R.","Na Sdarowje","In der Waldschenke"),
  (085,03,"Duval, Uve","Na Sdarowje","Schenk' mir einen Wodka ein"),
  (085,04,"Traditional","Na Sdarowje","Im tiefen Keller"),
  (085,05,"Hauptmann, D.","Na Sdarowje","Balalaika-Moritat"),
  (085,06,"Rebroff, Ivan","Na Sdarowje","Wladimir's Tafelrunde"),
  (085,07,"Duval, Uve","Na Sdarowje","Nidschewo"),
  (085,08,"Schubert, Franz P.","Schubert Mass E Flat","Kyrie"),
  (085,09,"Schubert, Franz P.","Schubert Mass E Flat","Gloria"),
  (085,10,"Schubert, Franz P.","Schubert Mass E Flat","Credo"),
  (085,11,"Schubert, Franz P.","Schubert Mass E Flat","Sanctus"),
  (085,12,"Schubert, Franz P.","Schubert Mass E Flat","Benedictus"),
  (085,13,"Schubert, Franz P.","Schubert Mass E Flat","Agnus Dei"),
  (086,01,"Schubert, Franz P.","Fair Maid of The Mill","Wandering"),
  (086,02,"Schubert, Franz P.","Fair Maid of The Mill","Whither"),
  (086,03,"Schubert, Franz P.","Fair Maid of The Mill","Halt!"),
  (086,04,"Schubert, Franz P.","Fair Maid of The Mill","Thanks to The Brook"),
  (086,05,"Schubert, Franz P.","Fair Maid of The Mill","Evening Rest"),
  (086,06,"Schubert, Franz P.","Fair Maid of The Mill","The Question"),
  (086,07,"Schubert, Franz P.","Fair Maid of The Mill","Impatience"),
  (086,08,"Schubert, Franz P.","Fair Maid of The Mill","A Morning Greeting"),
  (086,09,"Schubert, Franz P.","Fair Maid of The Mill","The Miller's Flowers"),
  (086,10,"Schubert, Franz P.","Fair Maid of The Mill","Shower of Tears"),
  (086,11,"Schubert, Franz P.","Fair Maid of The Mill","Mine"),
  (086,12,"Schubert, Franz P.","Fair Maid of The Mill","Pause"),
  (086,13,"Schubert, Franz P.","Fair Maid of The Mill","With The Lute's Green Ribbon"),
  (086,14,"Schubert, Franz P.","Fair Maid of The Mill","The Huntsman"),
  (086,15,"Schubert, Franz P.","Fair Maid of The Mill","Jealousy and Pride"),
  (086,16,"Schubert, Franz P.","Fair Maid of The Mill","The Favourite Colour"),
  (086,17,"Schubert, Franz P.","Fair Maid of The Mill","The Hateful Colour"),
  (086,18,"Schubert, Franz P.","Fair Maid of The Mill","Withered Flowers"),
  (086,19,"Schubert, Franz P.","Fair Maid of The Mill","The Miller and The Brook"),
  (086,20,"Schubert, Franz P.","Fair Maid of The Mill","The Brook's Lullaby"),
  (086,21,"Schuetz, Heinrich","Schuetz Magnificat","Magnificant"),
  (086,22,"Schuetz, Heinrich","Schuetz Magnificat","Et exultavit"),
  (086,23,"Schuetz, Heinrich","Schuetz Magnificat","Quia respexit"),
  (086,24,"Schuetz, Heinrich","Schuetz Magnificat","Quia fecit, Et Misericordia"),
  (086,25,"Schuetz, Heinrich","Schuetz Magnificat","Fecit Potentiam"),
  (086,26,"Schuetz, Heinrich","Schuetz Magnificat","Deposuit"),
  (086,27,"Schuetz, Heinrich","Schuetz Magnificat","Esurientes"),
  (086,28,"Schuetz, Heinrich","Schuetz Magnificat","Suspecit Israel"),
  (086,29,"Schuetz, Heinrich","Schuetz Magnificat","Sicut Locutus"),
  (086,30,"Schuetz, Heinrich","Schuetz Magnificat","Gloria Patri"),
  (086,31,"Schuetz, Heinrich","Schuetz Magnificat","Sicut erat"),
  (087,01,"Schuetz, Heinrich","Schuetz Musical Obsequies","Nacket bin ich von Mutterleibe kommen"),
  (087,02,"Schuetz, Heinrich","Schuetz Musical Obsequies","Er ist das Heil"),
  (087,03,"Schuetz, Heinrich","Schuetz Musical Obsequies","Herr, wenn ich nur dich habe"),
  (087,04,"Schuetz, Heinrich","Schuetz Musical Obsequies","Herr, nun laessest du deinen Diener"),
  (087,05,"Schuetz, Heinrich","Schuetz German Mass","German Mass"),
  (087,06,"Stravinsky, Igor F.","The Wedding","The Tress"),
  (087,07,"Stravinsky, Igor F.","The Wedding","The Bridegroom"),
  (087,08,"Stravinsky, Igor F.","The Wedding","Departure of The Bride"),
  (087,09,"Stravinsky, Igor F.","The Wedding","The Wedding Feast"),
  (087,10,"Stravinsky, Igor F.","The Soldier's Tale","The Soldier's March"),
  (087,11,"Stravinsky, Igor F.","The Soldier's Tale","Dancing Tunes"),
  (088,01,"Stravinsky, Igor F.","The Soldier's Tale","The Royal March"),
  (088,02,"Stravinsky, Igor F.","The Soldier's Tale","The Little Concert"),
  (088,03,"Stravinsky, Igor F.","The Soldier's Tale","Three Dances"),
  (088,04,"Stravinsky, Igor F.","The Soldier's Tale","The Devil's Dance"),
  (088,05,"Stravinsky, Igor F.","The Soldier's Tale","Great Chorale"),
  (088,06,"Stravinsky, Igor F.","The Soldier's Tale","Triumphant March of The Devil"),
  (088,07,"Verdi, Giuseppe","Verdi Requiem","Requiem Aeternam"),
  (088,08,"Verdi, Giuseppe","Verdi Requiem","Kyrie eleison"),
  (088,09,"Verdi, Giuseppe","Verdi Requiem","Dies Irae"),
  (088,10,"Verdi, Giuseppe","Verdi Requiem","Mors stupebit"),
  (088,11,"Verdi, Giuseppe","Verdi Requiem","Liber Scriptus proferetur"),
  (088,12,"Verdi, Giuseppe","Verdi Requiem","Quie Miser sum"),
  (088,13,"Verdi, Giuseppe","Verdi Requiem","Rex Tremendae Majestatis"),
  (088,14,"Verdi, Giuseppe","Verdi Requiem","Recordare"),
  (088,15,"Verdi, Giuseppe","Verdi Requiem","Ingemisco"),
  (088,16,"Verdi, Giuseppe","Verdi Requiem","Confutatis Maledictus"),
  (088,17,"Verdi, Giuseppe","Verdi Requiem","Dies Irae"),
  (088,18,"Verdi, Giuseppe","Verdi Requiem","Lacrymosa"),
  (089,01,"Verdi, Giuseppe","Verdi Requiem","Domine Jesu Christe"),
  (089,02,"Verdi, Giuseppe","Verdi Requiem","Hostias"),
  (089,03,"Verdi, Giuseppe","Verdi Requiem","Sanctus"),
  (089,04,"Verdi, Giuseppe","Verdi Requiem","Agnus Dei"),
  (089,05,"Verdi, Giuseppe","Verdi Requiem","Lux Aeterna"),
  (089,06,"Verdi, Giuseppe","Verdi Requiem","Requiem Aeternam"),
  (089,07,"Verdi, Giuseppe","Verdi Requiem","Libera Me"),
  (089,08,"Verdi, Giuseppe","Verdi Requiem","Tremens Factus sum"),
  (089,09,"Verdi, Giuseppe","Verdi Requiem","Dies Irae"),
  (089,10,"Verdi, Giuseppe","Verdi Requiem","Requiem Aeternam"),
  (089,11,"Verdi, Giuseppe","Verdi Requiem","Libera Me"),
  (089,12,"Vivaldi, Antonio","Vivaldi Gloria","Gloria"),
  (089,13,"Vivaldi, Antonio","Vivaldi Gloria","Et in Terra Pax Hominibus"),
  (089,14,"Vivaldi, Antonio","Vivaldi Gloria","Laduamus Te"),
  (089,15,"Vivaldi, Antonio","Vivaldi Gloria","Gratias agimus Tibi"),
  (089,16,"Vivaldi, Antonio","Vivaldi Gloria","Domine Deus, Rex Caelestis"),
  (089,17,"Vivaldi, Antonio","Vivaldi Gloria","Domine Deus, Unigenite Jesu Christe"),
  (089,18,"Vivaldi, Antonio","Vivaldi Gloria","Domine Deus, Agnus Dei"),
  (089,19,"Pergolesi, Giovanni B.","Pergolesi Magnificat","Qui sedes ad Dexteram Patris"),
  (089,20,"Pergolesi, Giovanni B.","Pergolesi Magnificat","Gloria Tu Solus Sanctus"),
  (089,21,"Pergolesi, Giovanni B.","Pergolesi Magnificat","Cum Sancto Spiritu"),
  (090,01,"Pergolesi, Giovanni B.","Pergolesi Magnificat","Magnificat"),
  (090,02,"Pergolesi, Giovanni B.","Pergolesi Magnificat","Et Misericordia"),
  (090,03,"Pergolesi, Giovanni B.","Pergolesi Magnificat","Fecit potentiam"),
  (090,04,"Pergolesi, Giovanni B.","Pergolesi Magnificat","Deposuit"),
  (090,05,"Pergolesi, Giovanni B.","Pergolesi Magnificat","Suscepit Israel"),
  (090,06,"Pergolesi, Giovanni B.","Pergolesi Magnificat","Sicut Locutus"),
  (090,07,"Pergolesi, Giovanni B.","Pergolesi Magnificat","Sicut erat"),
  (090,08,"Walton, William T.","Belshazzar's Feast","Thus spake Isaiah"),
  (090,09,"Walton, William T.","Belshazzar's Feast","By The Waters of Babylon"),
  (090,10,"Walton, William T.","Belshazzar's Feast","For They that wasted Us"),
  (090,11,"Walton, William T.","Belshazzar's Feast","If I forget Thee"),
  (090,12,"Walton, William T.","Belshazzar's Feast","By The Waters of Babylon"),
  (090,13,"Walton, William T.","Belshazzar's Feast","Babylon was A Great City"),
  (090,14,"Walton, William T.","Belshazzar's Feast","In Babylon Belshazzar The King"),
  (090,15,"Walton, William T.","Belshazzar's Feast","Praise Ye"),
  (090,16,"Walton, William T.","Belshazzar's Feast","Thus in Babylon"),
  (090,17,"Walton, William T.","Belshazzar's Feast","And in that Same Hour"),
  (090,18,"Walton, William T.","Belshazzar's Feast","Then sing Aloud to God Our Strength")
;

-- commit all changes

COMMIT;

